-- Generiert von scripts/import-wger.ts am 2026-07-13T11:05:58.877Z
-- Quelle: wger.de API v2 (821 Übungen, CC-BY-SA) — nicht von Hand bearbeiten,
-- bei Bedarf Skript erneut laufen lassen (erzeugt eine neue, eigene Migrationsdatei).

insert into exercise_catalog (name_de, name_en, exercise_type, muscle_group, equipment, source, external_id)
values
  ('Step Jack', 'Step Jack', 'cardio', 'Cardio', 'Körpergewicht', 'wger', '1962'),
  ('Langsame Kniebeuge', 'Slow Squat', 'strength', 'Beine', 'Körpergewicht', 'wger', '1963'),
  ('Breiter Liegestütz', 'Wide Push-Up', 'strength', 'Brust', 'Körpergewicht', 'wger', '1964'),
  ('Knieheben im Stand', 'Marching High Knees', 'strength', 'Beine', 'Körpergewicht', 'wger', '1965'),
  ('Steigungen', 'Step-ups', 'strength', 'Beine', 'Bank', 'wger', '981'),
  ('Brustwirbelsäulen-Rotation im halben Kniestand', '1/2 Kneeling Thoracic Rotation', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1966'),
  ('lento avanti seduto', 'lento avanti seduto', 'strength', 'Rücken', 'Kurzhantel', 'wger', '1967'),
  ('Einarmiges Schulterdrücken mit Kurzhantel', 'Single-arm dumbbell shoulder press', 'strength', 'Schultern', 'Kurzhantel', 'wger', '1968'),
  ('Kettlebell Sumo High Pull', 'Kettlebell sumo high pull', 'strength', 'Rücken', 'Kettlebell', 'wger', '1970'),
  ('Mentzer-Latzug', 'Mentzer Pulldown', 'strength', 'Arme', 'Schrägbank', 'wger', '1971'),
  ('Einarmiger Latzug', 'Single-Arm Lat Pulldown', 'strength', 'Rücken', null, 'wger', '1972'),
  ('Single Arm Plank to Row', 'Single Arm Plank to Row', 'strength', 'Rücken', 'Kettlebell', 'wger', '1022'),
  ('Hip Airplane', 'Hip Airplane', 'strength', 'Beine', 'Kettlebell', 'wger', '2447'),
  ('Curl De Muñeca Con Barra', 'Curl De Muñeca Con Barra', 'strength', 'Arme', 'Langhantel, Bank', 'wger', '2452'),
  ('YTW Raises', 'YTW Raises', 'strength', 'Schultern', 'Körpergewicht', 'wger', '2454'),
  ('Anterior Deltoid Press', 'Anterior Deltoid Press', 'strength', 'Schultern', 'Langhantel', 'wger', '2455'),
  ('Seated Hamstring Curl', 'Seated Hamstring Curl', 'strength', 'Beine', null, 'wger', '2456'),
  ('Suspended crossess', 'Suspended crossess', 'cardio', 'Cardio', 'Körpergewicht', 'wger', '927'),
  ('Knie hoch', 'High knees', 'cardio', 'Cardio', 'Körpergewicht', 'wger', '983'),
  ('Liegestütz-Drehungen', 'Push-up rotations', 'strength', 'Arme', 'Körpergewicht', 'wger', '985'),
  ('Kniende Rückschläge', 'Kneeling kickbacks', 'strength', 'Beine', 'Körpergewicht', 'wger', '990'),
  ('Seilspringen: Grundsprünge', 'Jump rope: basic jumps', 'cardio', 'Cardio', 'Körpergewicht', 'wger', '993'),
  ('Bergsteiger', 'Mountain climbers', 'strength', 'Brust', 'Körpergewicht', 'wger', '996'),
  ('Burpees mit 4 Zählzeiten', '4-count burpees', 'strength', 'Brust', 'Körpergewicht', 'wger', '997'),
  ('Axe Hold', 'Axe Hold', 'strength', 'Arme', 'Kurzhantel', 'wger', '31'),
  ('Trizepsdrücken am Kabelzug', 'Tricep Pushdown on Cable', 'strength', 'Arme', null, 'wger', '805'),
  ('Commando Pull-ups', 'commando pull-ups', 'strength', 'Bauch', 'Klimmzugstange', 'wger', '980'),
  ('Leisten hängen an 20 mm Kante', 'Fingerboard 20 mm edge', 'strength', 'Arme', null, 'wger', '820'),
  ('Reverse Fly auf der Schrägbank', 'Incline Bench Reverse Fly', 'strength', 'Rücken', 'Kurzhantel', 'wger', '828'),
  ('Zone 2 Running', 'Zone 2 Running', 'cardio', 'Cardio', null, 'wger', '908'),
  ('Lying Dumbbell Row SS Seated Shrug', 'Lying Dumbbell Row SS Seated Shrug', 'strength', 'Rücken', 'Kurzhantel', 'wger', '923'),
  ('Bizeps mit TRX', 'Biceps with TRX', 'strength', 'Bauch', 'Körpergewicht', 'wger', '958'),
  ('Kettlebell Swing', 'Kettlebell Swing', 'strength', 'Bauch', 'Kettlebell', 'wger', '960'),
  ('Swimming 50m sprints', 'Swimming 50m sprints', 'cardio', 'Cardio', null, 'wger', '961'),
  ('Bear Walk', 'Bear Walk 2', 'strength', 'Brust', 'Körpergewicht', 'wger', '57'),
  ('Einarmige Kettlebell-Curls', 'one-handed kettlebell curls', 'strength', 'Arme', 'Kettlebell', 'wger', '975'),
  ('Medicine ball booklet crunch', 'Medicine ball booklet crunch', 'strength', 'Bauch', 'Körpergewicht', 'wger', '976'),
  ('Box Squat', 'Box squat', 'strength', 'Bauch', 'Körpergewicht', 'wger', '977'),
  ('Knee Raises', 'Knee Raises', 'strength', 'Bauch', 'Klimmzugstange', 'wger', '978'),
  ('Sloper hängen', 'Sloper hanging', 'strength', 'Arme', 'Körpergewicht', 'wger', '804'),
  ('Rollout mit der Langhantel', 'Barbell Ab Rollout', 'strength', 'Bauch', 'Langhantel', 'wger', '41'),
  ('Crosstrainer', 'Elliptical', 'cardio', 'Cardio', 'Körpergewicht', 'wger', '962'),
  ('Klimmzug an Leiste', 'Pullup on fingerboard', 'strength', 'Arme', 'Körpergewicht', 'wger', '821'),
  ('Reverse Nordic Curl', 'Reverse Nordic Curl', 'strength', 'Beine', null, 'wger', '909'),
  ('Straight Bar Cable Curls', 'Straight Bar Cable Curls', 'strength', 'Arme', null, 'wger', '912'),
  ('TRX Rows', 'TRX Rows', 'strength', 'Bauch', 'Körpergewicht', 'wger', '959'),
  ('Leg raises pull up bar', 'Leg raises pull up bar', 'strength', 'Bauch', 'Klimmzugstange', 'wger', '979'),
  ('Body-Ups', 'Body-Ups', 'strength', 'Arme', 'Körpergewicht', 'wger', '112'),
  ('Vorgebeugtes High Pull', 'Bent High Pulls', 'strength', 'Schultern', 'Kurzhantel', 'wger', '79'),
  ('Blaze', 'Blaze', 'cardio', 'Cardio', 'Bank, Kurzhantel, Kettlebell, Körpergewicht', 'wger', '1630'),
  ('Einarmiges Trizepsdrücken am Kabelzug', 'Single-arm cable pushdown', 'strength', 'Arme', null, 'wger', '1969'),
  ('Reverse Clamshell', 'Reverse Clamshell', 'strength', 'Beine', 'Körpergewicht', 'wger', '2448'),
  ('Keine Liegestütz-Burpees', 'No push-up burpees', 'strength', 'Brust', 'Körpergewicht', 'wger', '998'),
  ('Bodensenken', 'Floor dips', 'strength', 'Arme', 'Körpergewicht', 'wger', '1000'),
  ('Kinderpose', 'Child''s pose', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1002'),
  ('Kettlebell Kreuzheben', 'Kettlebell deadlifts', 'strength', 'Rücken', 'Kettlebell', 'wger', '1003'),
  ('Schluckübungen', 'Chin tuck', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1006'),
  ('Kopf drehen', 'Head turns', 'strength', 'Schultern', 'Körpergewicht', 'wger', '1007'),
  ('Nackendehnung', 'Back neck stretch', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1010'),
  ('Abwechselnde Bizepscurls', 'Alternating bicep curls', 'strength', 'Arme', 'Kurzhantel', 'wger', '1012'),
  ('Kopf neigen', 'Head tilts', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1018'),
  ('Barbell Lunges Walking', 'Barbell Lunges Walking', 'strength', 'Beine', 'Langhantel', 'wger', '802'),
  ('Ausfallschritte', 'Lunges', 'strength', 'Beine', 'Körpergewicht', 'wger', '984'),
  ('Seitliche Kniebeugen links', 'Side split squats left', 'strength', 'Beine', 'Körpergewicht', 'wger', '986'),
  ('Seitliche Kniebeugen rechts', 'Side split squats right', 'strength', 'Beine', 'Körpergewicht', 'wger', '987'),
  ('Bulgarische geteilte Kniebeugen links', 'Bulgarian split squats left', 'strength', 'Beine', 'Körpergewicht', 'wger', '988'),
  ('Bulgarische geteilte Kniebeugen rechts', 'Bulgarian split squats right', 'strength', 'Beine', 'Körpergewicht', 'wger', '989'),
  ('Geteilte Kniebeugen links', 'Split squats left', 'strength', 'Beine', 'Körpergewicht', 'wger', '991'),
  ('Geteilte Kniebeugen rechts', 'Split squats right', 'strength', 'Beine', 'Körpergewicht', 'wger', '992'),
  ('Armkreisen vorwärts', 'Forward arm circles', 'strength', 'Arme', 'Körpergewicht', 'wger', '994'),
  ('Armkreisen rückwärts', 'Backward arm circles', 'strength', 'Arme', 'Körpergewicht', 'wger', '995'),
  ('Umgekehrte Ausfallschritte', 'Reverse lunges', 'strength', 'Beine', 'Körpergewicht', 'wger', '999'),
  ('Hohe Planke', 'High plank', 'strength', 'Brust', 'Körpergewicht', 'wger', '1001'),
  ('Vorwärtsdrehung der Schulter', 'Forward shoulder rotation', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1004'),
  ('Rückwärtsdrehung der Schulter', 'Backward shoulder rotation', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1005'),
  ('Linke Nackendehnung', 'Left neck stretch', 'strength', 'Schultern', 'Körpergewicht', 'wger', '1008'),
  ('Rechte Nackendehnung', 'Right neck stretch', 'strength', 'Schultern', 'Körpergewicht', 'wger', '1009'),
  ('Dehnung des linken Schulterblattes', 'Left levator scapulae stretch', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1013'),
  ('Dehnung des rechten Schulterblattes', 'Right levator scapulae stretch', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1014'),
  ('Nordic Curl', 'Nordic Curl', 'strength', 'Beine', null, 'wger', '910'),
  ('Reverse Preacher Curl (Close Grip)', 'Reverse Preacher Curl (Close Grip)', 'strength', 'Arme', 'SZ-Stange', 'wger', '913'),
  ('Schrägbankdrücken an der Smith-Maschine', 'Smith Machine Slight Incline Press', 'strength', 'Brust', null, 'wger', '925'),
  ('Burpees', 'Burpees', 'strength', 'Brust', null, 'wger', '132'),
  ('Brustpresse', 'Chest Press', 'strength', 'Brust', null, 'wger', '129'),
  ('Pull-Over KH', 'Cross-Bench Dumbbell Pullovers', 'strength', 'Brust', 'Kurzhantel', 'wger', '161'),
  ('Deadhang', 'Deadhang', 'strength', 'Arme', null, 'wger', '182'),
  ('Fahrrad fahren', 'Cycling', 'cardio', 'Cardio', 'Körpergewicht', 'wger', '177'),
  ('Holzhacker am Kabelzug', 'Cable Woodchoppers', 'strength', 'Bauch', null, 'wger', '145'),
  ('Deadbug', 'Deadbug', 'strength', 'Bauch', null, 'wger', '178'),
  ('Chin-ups', 'Chin Up', 'strength', 'Rücken', 'Klimmzugstange', 'wger', '152'),
  ('Face Pulls', 'Facepull', 'strength', 'Schultern', null, 'wger', '222'),
  ('Reverse EZ Bar Cable Curls', 'Reverse EZ Bar Cable Curls', 'strength', 'Arme', 'SZ-Stange', 'wger', '914'),
  ('Machine chest fly', 'Machine chest fly', 'strength', 'Brust', null, 'wger', '926'),
  ('Dumbbells on Scott Machine', 'Dumbbells on Scott Machine', 'strength', 'Arme', null, 'wger', '208'),
  ('Hyperextensions', 'Hyperextensions', 'strength', 'Rücken', null, 'wger', '301'),
  ('Hohe Knie-Sprünge', 'High Knee Jumps', 'cardio', 'Cardio', null, 'wger', '285'),
  ('Bus Drivers', 'Bus Drivers', 'strength', 'Schultern', null, 'wger', '915'),
  ('Hand Grip', 'Hand Grip', 'strength', 'Arme', null, 'wger', '279'),
  ('Hüftheben in Rückenlage', 'Hip Raise, Lying', 'strength', 'Rücken', 'Körpergewicht', 'wger', '292'),
  ('Hercules Pillars', 'Hercules Pillars', 'strength', 'Arme', null, 'wger', '284'),
  ('Beckenheben', 'Hip Thrust', 'strength', 'Beine', 'Langhantel, Bank', 'wger', '294'),
  ('High Pull', 'High Pull', 'strength', 'Schultern', null, 'wger', '289'),
  ('Hollow Hold', 'Hollow Hold', 'strength', 'Bauch', 'Matte, Körpergewicht', 'wger', '297'),
  ('Clamshell zu Reverse Clamshell', 'Clamshell to Reverse Clamshell', 'strength', 'Beine', 'Körpergewicht', 'wger', '2449'),
  ('Halskreise im Uhrzeigersinn', 'Clockwise neck circles', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1015'),
  ('Nackenkreise gegen den Uhrzeigersinn', 'Counterclockwise neck circles', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1016'),
  ('Nacken-Halbkreise', 'Neck half circles', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1017'),
  ('Seitenplanke rechts', 'Side plank right', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1019'),
  ('Einbeinige Kniebeugen rechts', 'Pistol squats right', 'strength', 'Beine', 'Körpergewicht', 'wger', '1020'),
  ('Wadenheben rechtes Bein', 'Calf raises, right leg', 'strength', 'Waden', 'Körpergewicht', 'wger', '1021'),
  ('Seilzug-Pullover/Rudern', 'Rope Pullover/row', 'strength', 'Rücken', 'Schrägbank', 'wger', '1634'),
  ('Einarmiges Rudern', 'Single arm row', 'strength', 'Rücken', 'Schrägbank', 'wger', '1637'),
  ('Umsetzen und Drücken mit der Langhantel', 'Barbell Clean and press', 'strength', 'Schultern', 'Kurzhantel', 'wger', '1638'),
  ('Rudern KH Auf Schrägbank', 'Incline Dumbbell Row', 'strength', 'Rücken', 'Kurzhantel, Schrägbank', 'wger', '310'),
  ('Smith Press', 'Smith Press', 'strength', 'Schultern', 'Schrägbank', 'wger', '916'),
  ('Isometric Wipers', 'Isometric Wipers', 'strength', 'Brust', 'Körpergewicht', 'wger', '314'),
  ('Hampelmann', 'Jumping Jacks', 'strength', 'Beine', null, 'wger', '320'),
  ('Landmine-Press, Einarmig', 'Landmine press', 'strength', 'Schultern', 'Langhantel', 'wger', '346'),
  ('Kabelcross', 'Cable Cross-over', 'strength', 'Brust', null, 'wger', '323'),
  ('Joggen', 'Jogging', 'cardio', 'Cardio', null, 'wger', '319'),
  ('Long-Pulley (eng)', 'Long-Pulley, Narrow', 'strength', 'Rücken', null, 'wger', '395'),
  ('Straight Bar Cable Front Raise', 'Straight Bar Cable Front Raise', 'strength', 'Schultern', 'SZ-Stange', 'wger', '917'),
  ('Arm- und Beinheben im Vierfüßlerstand', 'Quadriped Arm and Leg Raise', 'strength', 'Rücken', 'Körpergewicht', 'wger', '957'),
  ('Long-Pulley', 'Long-Pulley (low Row)', 'strength', 'Rücken', null, 'wger', '394'),
  ('Rotatorenmanschette im Liegen', 'Lying Rotator Cuff Exercise', 'strength', 'Schultern', 'Kurzhantel', 'wger', '406'),
  ('Muscle-up', 'Muscle up', 'strength', 'Rücken', 'Klimmzugstange', 'wger', '423'),
  ('L Sit', 'L Hold', 'strength', 'Bauch', null, 'wger', '382'),
  ('Schulterblatt-Retraktion in Bauchlage – Arme seitlich', 'Prone Scapular Retraction - Arms at Side', 'strength', 'Rücken', null, 'wger', '468'),
  ('Hecht-Liegestütze', 'Pike Push Ups', 'strength', 'Arme', 'Körpergewicht', 'wger', '454'),
  ('Seated Dumbbell Side Lateral', 'Seated Dumbbell Side Lateral', 'strength', 'Schultern', 'Kurzhantel', 'wger', '918'),
  ('Overhand Cable Curl', 'Overhand Cable Curl', 'strength', 'Bauch', null, 'wger', '439'),
  ('Reverse Curls', 'Reverse Curl', 'strength', 'Arme', 'Langhantel, Kurzhantel', 'wger', '495'),
  ('T-Bar row', 'T-Bar row', 'strength', 'Rücken', 'Langhantel', 'wger', '919'),
  ('Rückenstrecker im Stehen', 'Front Wood Chop', 'strength', 'Rücken', null, 'wger', '516'),
  ('Beinheben am Roman Chair', 'Roman Chair Crunch', 'strength', 'Bauch', null, 'wger', '505'),
  ('Modified pulldown', 'Modified pulldown', 'strength', 'Rücken', 'Schrägbank', 'wger', '1635'),
  ('Brustwirbelsäulen-Rotation im Vierfüßlerstand rechts', 'Quadruped thoracic rotation right', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1029'),
  ('Face Pull mit Kurzhanteln in vorgebeugter Haltung', 'Dumbbell Bent Over Face Pull', 'strength', 'Rücken', 'Kurzhantel', 'wger', '1639'),
  ('Curl mit Kettlebell beidhändig', 'Curl with kettlebell two hands', 'strength', 'Arme', 'Kettlebell', 'wger', '974'),
  ('Brustdehnung im Türrahmen', 'Doorway Pectoral Stretch', 'strength', 'Brust', 'Körpergewicht', 'wger', '1713'),
  ('Rennen', 'Run', 'cardio', 'Cardio', null, 'wger', '527'),
  ('Schrägbankdrücken MP', 'Incline Bench Press - MP', 'strength', 'Brust', null, 'wger', '539'),
  ('Reverse Plank', 'Reverse Plank', 'strength', 'Bauch', null, 'wger', '500'),
  ('Seitliches Oberkörperbeugen Mit KH', 'Side Dumbbell Trunk Flexion', 'strength', 'Bauch', 'Kurzhantel', 'wger', '577'),
  ('Außenrotation in Seitenlage', 'Side-lying External Rotation', 'strength', 'Schultern', null, 'wger', '578'),
  ('Seilspringen', 'Skipping - Standard', 'cardio', 'Cardio', null, 'wger', '595'),
  ('Seitliches Oberkörperbeugen am Gerät', 'Side Bends on Machine', 'strength', 'Bauch', 'Kurzhantel', 'wger', '556'),
  ('Stationary Bike', 'Stationary Bike', 'cardio', 'Cardio', null, 'wger', '624'),
  ('Kick-Backs', 'Tricep Dumbbell Kickback', 'strength', 'Arme', 'Kurzhantel', 'wger', '655'),
  ('Superman', 'Superman', 'strength', 'Rücken', 'Matte', 'wger', '636'),
  ('Trizepsmaschine', 'Triceps on Machine', 'strength', 'Arme', null, 'wger', '661'),
  ('Unterarmtraining mit Rollstange im Stehen', 'Standing Rope Forearm', 'strength', 'Arme', null, 'wger', '623'),
  ('Turkish Get-Up', 'Turkish Get-Up', 'strength', 'Bauch', 'Kurzhantel', 'wger', '675'),
  ('Seated Cable Mid Trap Shrug', 'Seated Cable Mid Trap Shrug', 'strength', 'Rücken', null, 'wger', '922'),
  ('Umsetzen', 'Power Clean', 'strength', 'Brust', 'Langhantel', 'wger', '683'),
  ('Weighted Step-ups', 'Weighted Step-ups', 'strength', 'Beine', null, 'wger', '722'),
  ('Upper External Oblique', 'Upper External Oblique', 'strength', 'Brust', 'Klimmzugstange', 'wger', '688'),
  ('Trunk Rotation With Cable', 'Trunk Rotation With Cable', 'strength', 'Bauch', null, 'wger', '672'),
  ('Wandgleiten', 'Wall Slides', 'strength', 'Rücken', 'Körpergewicht', 'wger', '716'),
  ('Overhead Press', 'Overhead Press', 'strength', 'Brust', 'Langhantel', 'wger', '687'),
  ('Erhöhte Gebets-Dehnung', 'Elevated prayer stretch', 'strength', 'Rücken', 'Bank', 'wger', '1027'),
  ('Brustwirbelsäulen-Rotation im Vierfüßlerstand links', 'Quadruped thoracic rotation left', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1028'),
  ('Hindu-Liegestütze', 'Hindu Pushups', 'strength', 'Schultern', null, 'wger', '1080'),
  ('Schulterdislokationen', 'Shoulder dislocates', 'strength', 'Schultern', null, 'wger', '1081'),
  ('Vorgebeugtes Rudern mit Außenrotation', 'Bent over row to external rotation', 'strength', 'Rücken', null, 'wger', '1082'),
  ('YWTs', 'YWTs', 'strength', 'Rücken', null, 'wger', '1083'),
  ('Liegestütze mit engem Griff', 'Close-grip Press-ups', 'strength', 'Brust', 'Körpergewicht', 'wger', '1086'),
  ('Hang Power Cleans mit Kurzhanteln', 'Dumbbell Hang Power Cleans', 'strength', 'Rücken', 'Kurzhantel', 'wger', '1087'),
  ('Sumo-Kreuzheben mit Kurzhantel', 'Dumbbell sumo deadlift', 'strength', 'Beine', 'Kurzhantel', 'wger', '1088'),
  ('Medizinball-Drehung', 'Medicine ball twist', 'strength', 'Bauch', 'Gymnastikball', 'wger', '1089'),
  ('Vpushup', 'Vpushup', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1090'),
  ('Plank Shoulder Taps', 'Plank Shoulder Taps', 'strength', 'Bauch', 'Matte', 'wger', '1091'),
  ('Frontkniebeuge mit Kurzhanteln', 'Dumbbell Front Squat', 'strength', 'Beine', 'Kurzhantel', 'wger', '1640'),
  ('Walking', 'Walking', 'cardio', 'Cardio', 'Körpergewicht', 'wger', '1104'),
  ('Einbeiniges Kreuzheben mit Kettlebell', 'Kettlebell One Legged Deadlift', 'strength', 'Beine', 'Kurzhantel, Kettlebell', 'wger', '1641'),
  ('Hip Thrust mit Kurzhantel', 'Dumbbell Hip Thrust', 'strength', 'Beine', 'Kurzhantel', 'wger', '1642'),
  ('Crunch mit Zusatzgewicht', 'Weighted Crunch', 'strength', 'Bauch', 'Kurzhantel', 'wger', '1648'),
  ('Nackenstütze vorne', 'Front neck stretch', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1011'),
  ('Seitneigung mit Kurzhantel', 'Dumbbell Side Bend', 'strength', 'Bauch', 'Kurzhantel', 'wger', '1650'),
  ('Rückwärtiger Ausfallschritt mit Kurzhanteln', 'Dumbbell Rear Lunge', 'strength', 'Beine', 'Kurzhantel', 'wger', '1651'),
  ('Seitliche Kniebeuge mit Kurzhantel', 'Dumbbell Side Squat', 'strength', 'Beine', null, 'wger', '1653'),
  ('Seitheben an der Maschine', 'Machine Lateral Raise', 'strength', 'Schultern', 'Matte', 'wger', '1654'),
  ('Cycling cardio session', 'Cycling cardio session', 'cardio', 'Cardio', null, 'wger', '1204'),
  ('Rumänisches Kreuzheben mit Kurzhanteln', 'Dumbbell Romanian Deadlift', 'strength', 'Beine', 'Kurzhantel', 'wger', '1652'),
  ('Incline Skull Crush', 'Incline Skull Crush', 'strength', 'Arme', null, 'wger', '911'),
  ('2 Handed Kettlebell Swing', '2 Handed Kettlebell Swing', 'strength', 'Bauch', 'Kettlebell', 'wger', '9'),
  ('Rudergerät', 'Rowing Machine', 'cardio', 'Cardio', 'Körpergewicht', 'wger', '1093'),
  ('Brustpresse im Sitzen', 'Seated Bench Press', 'strength', 'Brust', 'Bank', 'wger', '1094'),
  ('Rudern Vorgebeugt LH Reverse', 'Bent Over Rowing Reverse', 'strength', 'Rücken', 'Langhantel', 'wger', '84'),
  ('Abduktion im Stand', 'Abduction while standing', 'strength', 'Beine', 'Körpergewicht', 'wger', '1096'),
  ('Seated rear delt rise', 'Seated rear delt rise', 'strength', 'Rücken', 'Kurzhantel', 'wger', '1098'),
  ('Dynamisches seitliches Halten', 'Dynamic side hold', 'strength', 'Bauch', 'Kettlebell', 'wger', '1099'),
  ('Wall balls', 'Wall balls', 'strength', 'Beine', 'Gymnastikball', 'wger', '1100'),
  ('Horizontal traction isometry', 'Horizontal traction isometry', 'strength', 'Bauch', 'Klimmzugstange', 'wger', '1101'),
  ('Alternate back lunges', 'Alternate back lunges', 'strength', 'Beine', 'Körpergewicht', 'wger', '1102'),
  ('Wandernde Brücke', 'walking bridge', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1103'),
  ('Seated Knee Tuck', 'Seated Knee Tuck', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1105'),
  ('Konzentrationscurl am Kabelzug', 'Cable Concentration Curl', 'strength', 'Arme', null, 'wger', '1109'),
  ('Liegestütze | erhöht (Incline)', 'Push-Ups | Incline', 'strength', 'Brust', 'Bank, Schrägbank', 'wger', '1111'),
  ('Liegestütze | abfallend (Decline)', 'Push-Ups | Decline', 'strength', 'Brust', 'Bank, Schrägbank', 'wger', '1112')
on conflict (external_id) where external_id is not null do update set
  name_de = excluded.name_de,
  name_en = excluded.name_en,
  exercise_type = excluded.exercise_type,
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  updated_at = now();

insert into exercise_catalog (name_de, name_en, exercise_type, muscle_group, equipment, source, external_id)
values
  ('Liegestütze | Parallettes', 'Push-Ups | Parallettes', 'strength', 'Brust', null, 'wger', '1113'),
  ('Rest (for timed workouts)', 'Rest (for timed workouts)', 'strength', 'Arme', null, 'wger', '1114'),
  ('3D-Ausfallschritt zum Aufwärmen', '3D lunge warmup', 'cardio', 'Cardio', 'Kurzhantel', 'wger', '1115'),
  ('Dumbbell farmer''s carry', 'Dumbbell farmer''s carry', 'strength', 'Beine', 'Kurzhantel', 'wger', '1116'),
  ('Remo maquina agarre estrecho', 'Remo maquina agarre estrecho', 'strength', 'Rücken', null, 'wger', '1119'),
  ('Remo maquina agarre estrecho supino', 'Remo maquina agarre estrecho supino', 'strength', 'Rücken', null, 'wger', '1120'),
  ('Latzug mit weitem Untergriff', 'Wide-grip supinated lat pulldown', 'strength', 'Rücken', null, 'wger', '1125'),
  ('Latzug mit engem Untergriff', 'Close-grip supinated lat pulldown', 'strength', 'Rücken', null, 'wger', '1127'),
  ('Gesäßstrecken am Kabelzug', 'Cable glute extension', 'strength', 'Beine', null, 'wger', '1131'),
  ('Gesäßstrecken an der Maschine', 'Machine glute extension', 'strength', 'Beine', null, 'wger', '1132'),
  ('Latzug zur Brust mit neutralem Griff', 'Neutral-grip chest pulldown', 'strength', 'Rücken', null, 'wger', '1136'),
  ('Pullover am hohen Kabelzug', 'High-pulley pullover', 'strength', 'Rücken', null, 'wger', '1137'),
  ('Incline bench pulldown', 'Incline bench pulldown', 'strength', 'Rücken', null, 'wger', '1138'),
  ('Arabeske', 'Arabesque', 'strength', 'Beine', 'Körpergewicht', 'wger', '1141'),
  ('Back extensión', 'Back extensión', 'strength', 'Rücken', null, 'wger', '1143'),
  ('Triceps Pushdown', 'Triceps Pushdown', 'strength', 'Arme', null, 'wger', '1185'),
  ('One Arm Bent Row', 'One Arm Bent Row', 'strength', 'Rücken', null, 'wger', '1186'),
  ('Alternierende Bizeps-Curls mit Kurzhantel', 'Alternating Biceps Curls With Dumbbell', 'strength', 'Arme', 'Kurzhantel', 'wger', '1192'),
  ('Russian Twist', 'Russian Twist', 'strength', 'Bauch', 'Kurzhantel, Matte, Gymnastikball', 'wger', '1193'),
  ('Pallof Press', 'Pallof Press', 'strength', 'Bauch', null, 'wger', '1194'),
  ('Seitliche Slides + Kniebeugen', 'Side Slides + Squats', 'strength', 'Beine', 'Körpergewicht', 'wger', '1195'),
  ('Wand-Drills', 'Wall Drills', 'strength', 'Beine', 'Körpergewicht', 'wger', '1196'),
  ('Inverted Rows (umgekehrtes Rudern)', 'Inverted Rows', 'strength', 'Brust', 'Körpergewicht', 'wger', '1198'),
  ('Tibialis raises', 'Tibialis raises', 'strength', 'Waden', 'Körpergewicht', 'wger', '1200'),
  ('Dragon Squat', 'Dragon squat', 'strength', 'Beine', 'Körpergewicht', 'wger', '1201'),
  ('Hüftabduktion in Seitenlage', 'Side Lying Hip Abduction', 'strength', 'Beine', 'Körpergewicht', 'wger', '1202'),
  ('Wadenheben, linkes Bein', 'Calf raises, left leg', 'strength', 'Waden', 'Körpergewicht', 'wger', '1203'),
  ('Handgelenk-Curl mit Kurzhanteln', 'Wrist curl, dumbbells', 'strength', 'Arme', 'Kurzhantel', 'wger', '1205'),
  ('Skorpion-Kick', 'Scorpion Kick', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1207'),
  ('Prisoner Squat', 'Prisoner Squat', 'strength', 'Beine', 'Körpergewicht', 'wger', '1208'),
  ('Fallschirmspringer in T-Position', 'Skydiver with arms in T-position', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1210'),
  ('Full Sit Outs', 'Full Sit Outs', 'strength', 'Bauch', 'Körpergewicht', 'wger', '260'),
  ('Reverse Snow Angel', 'Reverse Snow Angel', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1215'),
  ('Liegestütze auf den Knien', 'knee push-ups', 'strength', 'Arme', 'Körpergewicht', 'wger', '1218'),
  ('Australian Pull-ups (umgekehrtes Rudern)', 'Australian pull-ups', 'strength', 'Arme', 'Körpergewicht', 'wger', '1219'),
  ('Brustdrücken am Kabelzug - negativ geneigt', 'Cable Chest Press - Decline', 'strength', 'Brust', null, 'wger', '1656'),
  ('Pendelübung für die Schulter mit Kurzhantel', 'Shoulder Dumbbell Pendular Exercise', 'strength', 'Schultern', 'Kurzhantel', 'wger', '1714'),
  ('Außenrotation der Schulter mit Kurzhantel', 'Shoulder External Rotation with Dumbbell', 'strength', 'Schultern', 'Kurzhantel', 'wger', '1715'),
  ('Claps over the head', 'Claps over the head', 'strength', 'Arme', 'Körpergewicht', 'wger', '1223'),
  ('Kurzhantel-Drag-Curls', 'Dumbbell drag curls', 'strength', 'Arme', 'Kurzhantel', 'wger', '1224'),
  ('Beinstrecker (Leg Extension)', 'Leg Extension', 'strength', 'Beine', null, 'wger', '369'),
  ('Schulterdrücken auf der Bank (Scapular Push-up)', 'Incline Shoulder Press Up', 'strength', 'Brust', 'Bank', 'wger', '1716'),
  ('Breite Bizeps-Curls mit Kurzhanteln', 'Dumbbell wide bicep curls', 'strength', 'Arme', 'Kurzhantel', 'wger', '1225'),
  ('Neck extension', 'Neck extension', 'strength', 'Arme', 'SZ-Stange', 'wger', '1717'),
  ('Kurzhantel-Bizeps-Curl mit Schulterdrücken', 'Dumbbell bicep curl to press', 'strength', 'Arme', 'Kurzhantel', 'wger', '1226'),
  ('Kurzhantel-Rudern für die hintere Schulter', 'Dumbbell rear delt row', 'strength', 'Schultern', 'Kurzhantel', 'wger', '1227'),
  ('Kurzhantel-Bankdrücken im engen Griff', 'Dumbbell close grip bench press', 'strength', 'Arme', 'Kurzhantel', 'wger', '1228'),
  ('Reißen (Snatch)', 'Snatch', 'strength', 'Schultern', 'Langhantel', 'wger', '599'),
  ('Recruitment Pulls', 'Recruitment Pulls', 'strength', 'Arme', null, 'wger', '1216'),
  ('Trizepsdehnung links', 'Triceps stretch left', 'strength', 'Arme', 'Körpergewicht', 'wger', '1230'),
  ('Trizepsdehnung rechts', 'Triceps stretch right', 'strength', 'Arme', 'Körpergewicht', 'wger', '1231'),
  ('Stehende Bizepsdehnung links', 'Standing biceps stretch left', 'strength', 'Arme', 'Körpergewicht', 'wger', '1232'),
  ('Stehende Bizepsdehnung rechts', 'Standing biceps stretch right', 'strength', 'Arme', null, 'wger', '1233'),
  ('Einbeiniger Hip Thrust mit Kurzhantel', 'Dumbbell Single-leg Hip Thrust', 'strength', 'Beine', 'Langhantel', 'wger', '1234'),
  ('Remo alto polea alta', 'Remo alto polea alta', 'strength', 'Rücken', 'Langhantel', 'wger', '1718'),
  ('Fingerliegestütz', 'Finger Pushup', 'strength', 'Arme', 'Körpergewicht', 'wger', '1217'),
  ('Froschstand', 'Frog stand', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1238'),
  ('Stehende Wadendehnung', 'Standing Calf Stretch', 'strength', 'Beine', 'Körpergewicht', 'wger', '1239'),
  ('Sandsacktraining', 'Bag training', 'cardio', 'Cardio', 'Körpergewicht', 'wger', '1092'),
  ('Standing Soleus Stretch', 'Standing Soleus Stretch', 'strength', 'Beine', 'Körpergewicht', 'wger', '1240'),
  ('Exercise Band Dorsiflexion', 'Exercise Band Dorsiflexion', 'strength', 'Beine', 'Körpergewicht', 'wger', '1241'),
  ('Sitzendes Rudern am Kabelzug', 'Seated Cable Row', 'strength', 'Rücken', null, 'wger', '1117'),
  ('Plantarflexion mit Widerstandsband', 'Exercise Band Plantarflexion', 'strength', 'Beine', 'Körpergewicht', 'wger', '1242'),
  ('Beidbeiniges Wadenheben', 'Double Leg Calf Raise', 'strength', 'Beine', 'Körpergewicht', 'wger', '1243'),
  ('Yoga-Übung: Katze-Kuh', 'Yoga exercise: Cow-cat', 'strength', 'Rücken', 'Matte', 'wger', '1244'),
  ('Front Lever', 'Front Lever', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1245'),
  ('Schulterbreite Dreipunkt-Liegestütze', 'Shoulder width three-point push-up', 'strength', 'Arme', 'Körpergewicht', 'wger', '1209'),
  ('TRX Roll-out', 'TRX roll out', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1246'),
  ('Ice Scream Maker', 'Ice cream maker', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1248'),
  ('Front lever pull-up', 'Front lever pull-up', 'strength', 'Bauch', 'Klimmzugstange', 'wger', '1252'),
  ('Front Lever Tuck', 'Front lever tuck', 'strength', 'Rücken', 'Klimmzugstange', 'wger', '1214'),
  ('TRX Bauchmuskeln seitlich', 'TRX Obliques', 'strength', 'Bauch', null, 'wger', '1259'),
  ('TRX Hammer-Curl', 'TRX hammer curl', 'strength', 'Arme', null, 'wger', '1260'),
  ('Außenrotation am Kabelzug', 'Cable External Rotation', 'strength', 'Schultern', null, 'wger', '142'),
  ('TRX Gorilla-Bizeps-Curl', 'TRX gorilla biceps curl', 'strength', 'Arme', null, 'wger', '1261'),
  ('TRX einarmiger Bizeps-Curl', 'Trx Single Arm Bicep Curl', 'strength', 'Arme', null, 'wger', '1262'),
  ('Rückenbrücke', 'Back bridge', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1263'),
  ('TRX Trizepsstrecken', 'TRX Tricep Extension', 'strength', 'Arme', null, 'wger', '1266'),
  ('TRX Dips', 'TRX dips', 'strength', 'Arme', null, 'wger', '1269'),
  ('Kabel-Fly am unteren Kabelzug', 'Low Pulley Cable Fly', 'strength', 'Brust', null, 'wger', '1270'),
  ('Pullover', 'Pullover', 'strength', 'Rücken', 'Kurzhantel', 'wger', '1273'),
  ('Sitting Calf Stretch (Dorsiflexion)', 'Sitting Calf Stretch (Dorsiflexion)', 'strength', 'Beine', null, 'wger', '1274'),
  ('Plantarflexion Stretch with Band', 'Plantarflexion Stretch with Band', 'strength', 'Beine', null, 'wger', '1275'),
  ('Bizeps-Latzug mit engem Griff', 'Biceps Close Grip Pull Down', 'strength', 'Arme', null, 'wger', '1280'),
  ('Isometria trazioni impugnatura inversa', 'Isometria trazioni impugnatura inversa', 'strength', 'Rücken', 'Klimmzugstange', 'wger', '1282'),
  ('Schrägbank-Kurzhantelrudern mit Brustauflage', 'Incline Chest-Supported Dumbbell Row', 'strength', 'Rücken', 'Bank, Kurzhantel', 'wger', '1283'),
  ('Pseudo-Planche-Liegestütz', 'Pseudo Planche Push-up', 'strength', 'Schultern', 'Körpergewicht', 'wger', '1284'),
  ('Talons fesses', 'Talons fesses', 'cardio', 'Cardio', 'Körpergewicht', 'wger', '1285'),
  ('Dynamische Planche', 'Dynamic Planche', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1286'),
  ('Reach-ups', 'Reach ups', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1287'),
  ('Dynamischer Seitstütz', 'Dynamic side plank', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1288'),
  ('Sitzende Kurzhantel-Curls', 'Seated Dumbbell Curls', 'strength', 'Arme', 'Kurzhantel', 'wger', '1289'),
  ('Langhantel-Curls im Obergriff', 'Reverse Grip Barbell Curls', 'strength', 'Arme', 'Langhantel', 'wger', '1290'),
  ('Reverse-grip pull-ups', 'Reverse-grip pull-ups', 'strength', 'Bauch', 'Klimmzugstange', 'wger', '1292'),
  ('One armed push-ups', 'One armed push-ups', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1293'),
  ('Single-leg hamstring curl', 'Single-leg hamstring curl', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1294'),
  ('Low-Cable Cross-Over am Kabelzug', 'Low-Cable Cross-Over - NB', 'strength', 'Brust', null, 'wger', '1296'),
  ('Trizepsstrecken über Kreuz am hohen Kabelzug', 'High-Cable Cross Tricep Extention - NB', 'strength', 'Arme', null, 'wger', '1298'),
  ('Scott-Curl mit Innenrotation', 'Preacher Curl - Internally Rotated', 'strength', 'Arme', 'Kurzhantel', 'wger', '1657'),
  ('Latzug einarmig über Kreuz', 'Lat Pulldown - Cross Body Single Arm', 'strength', 'Rücken', null, 'wger', '1659'),
  ('Brustdrücken am Kabelzug auf der Schrägbank', 'Cable Chest Press - Incline', 'strength', 'Brust', null, 'wger', '1660'),
  ('JM Press', 'JM Press', 'strength', 'Arme', 'Langhantel', 'wger', '1302'),
  ('Helms Row', 'Helms Row', 'strength', 'Rücken', 'Kurzhantel', 'wger', '1303'),
  ('Meadows Row', 'Meadows Row', 'strength', 'Rücken', 'Langhantel', 'wger', '1304'),
  ('Trizepsdrücken am Kabelzug', 'Cable Triceps Press', 'strength', 'Arme', null, 'wger', '1661'),
  ('Trizepsstrecken am Kabelzug mit Innenrotation', 'Cable Tri Extension - Internal Rotation', 'strength', 'Arme', null, 'wger', '1662'),
  ('Unterarmstütz (Plank)', 'Front Plank', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1307'),
  ('Curl mit angehobener Schulter', 'Curl  - With Shoulder Elevated', 'strength', 'Arme', 'Kurzhantel', 'wger', '1666'),
  ('Hampelmann HD', 'Jumping Jack HD', 'cardio', 'Cardio', 'Körpergewicht', 'wger', '1314'),
  ('Einbeiniges Kreuzheben mit gestreckten Beinen (Single Leg RDL)', 'Single Leg RDL', 'strength', 'Beine', 'Körpergewicht', 'wger', '1388'),
  ('High Knee Skips', 'High Knee Skips HD', 'cardio', 'Cardio', 'Körpergewicht', 'wger', '1318'),
  ('Bench Dips am Boden', 'Bench Dips On Floor HD', 'strength', 'Arme', 'Körpergewicht', 'wger', '1320'),
  ('Ausfallschritt mit Körpergewicht', 'Bodyweight lunge HD', 'strength', 'Beine', 'Körpergewicht', 'wger', '1324'),
  ('Lateral Push Off', 'Lateral Push Off', 'strength', 'Beine', 'Körpergewicht', 'wger', '1325'),
  ('Einarmiges Trizepsstrecken über Kopf am Kabelzug', 'One Arm Overhead Cable Tricep Extension', 'strength', 'Arme', 'Widerstandsband', 'wger', '1668'),
  ('Beinpendel (vor und zurück)', 'Leg Swings (Front–Back)', 'strength', 'Beine', 'Körpergewicht', 'wger', '1670'),
  ('Hüftabduktion sitzend', 'Seated Hip Abduction', 'strength', 'Beine', 'Körpergewicht', 'wger', '1672'),
  ('Forearm Curls (underhand grip)', 'Forearm Curls (underhand grip)', 'strength', 'Arme', 'Kurzhantel', 'wger', '1333'),
  ('Trizepsdrücken über Kopf (Kurzhantel)', 'Triceps Overhead (Dumbbell)', 'strength', 'Arme', 'Kurzhantel', 'wger', '1336'),
  ('Schulterheben (Kurzhantel)', 'Shoulder Raise (Dumbbell)', 'strength', 'Schultern', 'Kurzhantel', 'wger', '1338'),
  ('Wall Angels', 'Wall Angels', 'strength', 'Schultern', null, 'wger', '1679'),
  ('Figur-Vier-Dehnung im Sitzen', 'seated figure four', 'strength', 'Beine', 'Bank', 'wger', '1680'),
  ('Rückenstrecker (unterer Rücken)', 'Lower Back Extensions', 'strength', 'Rücken', null, 'wger', '1348'),
  ('Hex Press mit Kurzhanteln', 'Dumbbell Hex Press', 'strength', 'Brust', 'Kurzhantel', 'wger', '1353'),
  ('Doppeltes Kettlebell Clean and Press', 'Double Kettlebell Clean and Press', 'strength', 'Arme', 'Kettlebell', 'wger', '1360'),
  ('Double Kettlebell Front Squat', 'Double Kettlebell Front Squat', 'strength', 'Beine', 'Kettlebell', 'wger', '1361'),
  ('Blackroll', 'Blackroll', 'strength', 'Rücken', null, 'wger', '1363'),
  ('Dumbbell Split Squat', 'Dumbbell Split Squat', 'strength', 'Beine', 'Kurzhantel', 'wger', '1366'),
  ('Dumbbell Deadlift', 'Dumbbell Deadlift', 'strength', 'Beine', 'Kurzhantel', 'wger', '1370'),
  ('Boxsprünge', 'box jumps', 'cardio', 'Cardio', 'Körpergewicht', 'wger', '1373'),
  ('Bauch-Twist Gerät', 'Rotary Torso Machine', 'strength', 'Bauch', null, 'wger', '1374'),
  ('Recumbent Bike', 'Recumbent Bike', 'cardio', 'Cardio', null, 'wger', '1376'),
  ('Rumpfdrehung', 'Torso Twist', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1377'),
  ('Band Pull-Aparts', 'Band pull-aparts', 'strength', 'Rücken', null, 'wger', '1380'),
  ('Upper Back', 'Upper Back', 'strength', 'Rücken', null, 'wger', '1381'),
  ('Kniebeuge mit Körpergewicht', 'Bodyweight Squat HD', 'strength', 'Beine', 'Körpergewicht', 'wger', '1312'),
  ('Pullover Machine', 'Pullover Machine', 'strength', 'Rücken', null, 'wger', '1384'),
  ('Zottman-Curl', 'Zottman curl', 'strength', 'Arme', 'Kurzhantel', 'wger', '1683'),
  ('Thruster', 'Thruster', 'strength', 'Beine', 'Langhantel', 'wger', '650'),
  ('Hamstring-Kicks', 'Hamstring Kicks', 'strength', 'Beine', 'Körpergewicht', 'wger', '1387'),
  ('Zehenberührung', 'Toe Touch', 'strength', 'Beine', 'Körpergewicht', 'wger', '1390'),
  ('Kurzhantel-Thruster', 'Dumbbell Thruster', 'strength', 'Beine', 'Kurzhantel', 'wger', '1684'),
  ('Glute Bridge mit einarmigem Drücken', 'Glute Bridge Single-Arm Press', 'strength', 'Arme', 'Kurzhantel', 'wger', '1686'),
  ('Bear Crawl Pull Through', 'Bear crawl pull through', 'strength', 'Bauch', 'Kurzhantel', 'wger', '1687'),
  ('Triceps Dips (Assisted)', 'Triceps Dips (Assisted)', 'strength', 'Arme', null, 'wger', '1372'),
  ('Seitheben am Kabelzug (einarmig)', 'Cable Lateral Raises (Single Arm)', 'strength', 'Schultern', null, 'wger', '1378'),
  ('Elephant Walks', 'Elephant Walks', 'strength', 'Beine', 'Körpergewicht', 'wger', '1391'),
  ('Good Morning', 'Good Morning', 'strength', 'Beine', 'Körpergewicht', 'wger', '1392'),
  ('Einbeiniges Dehnen der hinteren Oberschenkelmuskulatur', 'Single Leg Hamstring Stretch', 'strength', 'Beine', 'Körpergewicht', 'wger', '1393'),
  ('Sit & Reach', 'Sit & Reach', 'strength', 'Rücken', 'Matte', 'wger', '1394'),
  ('Beinschwingen über Kreuz', 'Crossbody Leg Swings', 'strength', 'Beine', 'Körpergewicht', 'wger', '1395'),
  ('Stehender Pancake', 'Standing Pancake', 'strength', 'Beine', 'Körpergewicht', 'wger', '1396'),
  ('Hamstring Chokes', 'Hamstring Chokes', 'strength', 'Beine', 'Körpergewicht', 'wger', '1398'),
  ('Roll Down', 'Roll Down', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1399'),
  ('Dehnung der hinteren Oberschenkelmuskulatur über Kreuz', 'Crossbody Hamstring Stretch', 'strength', 'Beine', 'Körpergewicht', 'wger', '1400'),
  ('Scottcurl - nach außen rotiert', 'Preacher Curl - Externally Rotated', 'strength', 'Arme', 'Kurzhantel', 'wger', '1658'),
  ('Plank-to-Elbow Extension', 'Plank-to-Elbow Extension', 'strength', 'Bauch', null, 'wger', '1406'),
  ('Kosaken-Kniebeuge', 'Cossack squat', 'strength', 'Beine', null, 'wger', '1407'),
  ('Wandsitz', 'Wall-sit', 'strength', 'Beine', null, 'wger', '1408'),
  ('Dragon Flag', 'Dragon-flag', 'strength', 'Bauch', null, 'wger', '1409'),
  ('Plank with Alternating Leg Lift', 'Plank with Alternating Leg Lift', 'strength', 'Beine', 'Körpergewicht', 'wger', '1410'),
  ('Fersenberührungen', 'Heel Touches', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1411'),
  ('Bicycle Crunches', 'bicycle crunches', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1412'),
  ('Hack Squats', 'Hack Squats', 'strength', 'Beine', null, 'wger', '1414'),
  ('Kurzhantel-Crunches', 'Dumbbell Crunches', 'strength', 'Bauch', 'Kurzhantel', 'wger', '1415'),
  ('Bizepscurl-Maschine', 'Biceps Curl Machine', 'strength', 'Arme', null, 'wger', '1424'),
  ('Toe Taps', 'Toe Taps', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1425'),
  ('Stehende seitliche Crunches', 'Standing Side Crunches', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1426'),
  ('Schulterrotationen mit Kurzhantel', 'Dumbbell Shoulder Rotations', 'strength', 'Schultern', 'Kurzhantel', 'wger', '1429'),
  ('Plate Pinch Hold', 'Plate Pinch Hold', 'strength', 'Arme', null, 'wger', '1430'),
  ('Umgekehrte Holzhacker', 'Reverse Wood Chops', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1433'),
  ('Lat Pull DB', 'Lat Pull DB', 'strength', 'Rücken', 'Kurzhantel', 'wger', '1434'),
  ('Scapula Pulls', 'Scapula Pulls', 'strength', 'Rücken', 'Klimmzugstange', 'wger', '1435'),
  ('Pin Bench Press LH', 'Pin Bench Press BB', 'strength', 'Brust', 'Langhantel', 'wger', '1436'),
  ('Pin Squat', 'Pin Squat', 'strength', 'Beine', 'Langhantel', 'wger', '1437'),
  ('Clean', 'Clean', 'strength', 'Beine', 'Langhantel', 'wger', '1438'),
  ('Pin OHP', 'Pin OHP', 'strength', 'Schultern', 'Langhantel', 'wger', '1439'),
  ('Push Press', 'Push OHP', 'strength', 'Schultern', 'Langhantel', 'wger', '1440'),
  ('Schrägbank-Schulterdrücken mit Kurzhanteln', 'Incline OHP DB', 'strength', 'Schultern', 'Kurzhantel', 'wger', '1441'),
  ('Kreis-Press mit Kurzhanteln', 'Kreis Press DB', 'strength', 'Schultern', 'Kurzhantel', 'wger', '1442'),
  ('Seitheben und Frontheben mit Kurzhanteln', 'Shoulder Raise Side and Front DB', 'strength', 'Schultern', 'Kurzhantel', 'wger', '1443'),
  ('Jerk (Stoßen)', 'Jerk OL', 'strength', 'Schultern', 'Langhantel', 'wger', '1445'),
  ('Clean and Jerk OL', 'Clean and Jerk OL', 'strength', 'Schultern', 'Langhantel', 'wger', '1446'),
  ('Snatch (Reißen)', 'Snatch OL', 'strength', 'Rücken', 'Langhantel', 'wger', '1447'),
  ('Sitzender W-Curl', 'Seated W Curl', 'strength', 'Arme', 'Bank, Kurzhantel', 'wger', '1448'),
  ('ClimbMill', 'ClimbMill', 'cardio', 'Cardio', null, 'wger', '1449'),
  ('Kobra-Dehnung', 'Cobra Stretch', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1450'),
  ('Rumpfrotations-Dehnung', 'Torso rotation stretch', 'strength', 'Brust', 'Körpergewicht', 'wger', '1451'),
  ('Knie-zur-Brust-Dehnung', 'Knee to Chest Stretch', 'strength', 'Beine', 'Körpergewicht', 'wger', '1452'),
  ('Handtuch-Superman', 'Towel Superman', 'strength', 'Rücken', null, 'wger', '1455'),
  ('Cable Press Around', 'Cable Press Around', 'strength', 'Brust', null, 'wger', '1457'),
  ('Cross-Body Cable Y-Raise', 'Cross-Body Cable Y-Raise', 'strength', 'Rücken', null, 'wger', '1458'),
  ('Kurzhantel-Brustdrücken ohne Beineinsatz', 'No Leg Drive Dumbbell Chest Press', 'strength', 'Brust', 'Bank, Kurzhantel', 'wger', '1461'),
  ('punches', 'punches', 'strength', 'Arme', 'Körpergewicht', 'wger', '1462'),
  ('Kurzhantel-Rudern im Untergriff aus dem Dead Stop', 'Dumbbell Underhand Dead Row', 'strength', 'Arme', 'Kurzhantel', 'wger', '1463'),
  ('Hack Squats mit Pause', 'Pause Hack Squats', 'strength', 'Beine', null, 'wger', '1464'),
  ('Spider Curl', 'Spider Curl', 'strength', 'Arme', 'Schrägbank', 'wger', '1465'),
  ('Calf Raise using Hack Squat Machine', 'Calf Raise using Hack Squat Machine', 'strength', 'Beine', null, 'wger', '1466'),
  ('Incline Close Grip Barbell Bench Press', 'Incline Close Grip Barbell Bench Press', 'strength', 'Arme', 'Langhantel', 'wger', '1467'),
  ('Floor Skull Crusher', 'Floor Skull Crusher', 'strength', 'Arme', 'SZ-Stange', 'wger', '1468')
on conflict (external_id) where external_id is not null do update set
  name_de = excluded.name_de,
  name_en = excluded.name_en,
  exercise_type = excluded.exercise_type,
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  updated_at = now();

insert into exercise_catalog (name_de, name_en, exercise_type, muscle_group, equipment, source, external_id)
values
  ('Bent over Cable Flye', 'Bent over Cable Flye', 'strength', 'Brust', null, 'wger', '1469'),
  ('1-Arm Half-Kneeling Lat Pulldown', '1-Arm Half-Kneeling Lat Pulldown', 'strength', 'Rücken', null, 'wger', '1470'),
  ('Kroc Row', 'Kroc Row', 'strength', 'Rücken', null, 'wger', '1471'),
  ('Cable Shrug-In', 'Cable Shrug-In', 'strength', 'Schultern', null, 'wger', '1472'),
  ('Reverse Cable Flye', 'Reverse Cable Flye', 'strength', 'Rücken', null, 'wger', '1473'),
  ('W-Raise', 'W-Raise', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1474'),
  ('Black Widow Knee Slides', 'Black Widow Knee Slides', 'strength', 'Bauch', null, 'wger', '1475'),
  ('Butterfly Sit-up', 'Butterfly Sit Up', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1476'),
  ('Sitzender Korkenzieher', 'Seated Corkscrew', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1477'),
  ('Levitation Crunch', 'Levitation Crunch', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1478'),
  ('Sit-Ups (Ellenbogen zum Knie)', 'Sit Up Elbow Thrust', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1479'),
  ('Liegendes Trizepsstrecken', 'Lying Triceps Extensions', 'strength', 'Arme', 'Langhantel, Kurzhantel', 'wger', '1480'),
  ('Drag Pushdown', 'Drag Pushdown', 'strength', 'Arme', 'SZ-Stange', 'wger', '1481'),
  ('Kurzhantel-Cheat-Curl', 'Dumbbell Cheat Curl', 'strength', 'Arme', 'Kurzhantel', 'wger', '1482'),
  ('Bizeps-Curls-Trifecta', 'Bizeps Curls Trifecta', 'strength', 'Arme', 'Kurzhantel', 'wger', '1483'),
  ('Omni Cable Crossover', 'Omni Cable Cross-over', 'strength', 'Brust', 'SZ-Stange', 'wger', '1484'),
  ('Rocking Triceps Pushdown', 'Rocking Triceps Pushdown', 'strength', 'Arme', 'SZ-Stange', 'wger', '1485'),
  ('Abwechselndes hohes Kabelrudern', 'Alternating High Cable Row', 'strength', 'Rücken', null, 'wger', '1486'),
  ('Hyper Y-W-Kombination', 'Hyper Y W Combo', 'strength', 'Rücken', null, 'wger', '1487'),
  ('Plank Jacks', 'Plank Jacks', 'strength', 'Bauch', null, 'wger', '1489'),
  ('Liegender Trizeps-Kickback', 'Lying Triceps Kickback', 'strength', 'Arme', 'Kurzhantel, Schrägbank', 'wger', '1490'),
  ('High Row', 'High Row', 'strength', 'Rücken', null, 'wger', '1492'),
  ('Bayesian Curl', 'Bayesian Curl', 'strength', 'Arme', null, 'wger', '1493'),
  ('Kurzhantel-Variation für die obere Brust', 'DB Upper Chest Variation', 'strength', 'Brust', 'Kurzhantel', 'wger', '1496'),
  ('DB Underhand bench press', 'DB Underhand bench press', 'strength', 'Brust', 'Bank, Kurzhantel', 'wger', '1497'),
  ('Elbows Tucked DB Bench Press', 'Elbows Tucked DB Bench Press', 'strength', 'Arme', 'Bank, Kurzhantel', 'wger', '1498'),
  ('Alternatives Gorilla-Rudern mit Kurzhanteln', 'Alternative DB Gorilla rows', 'strength', 'Rücken', 'Kurzhantel', 'wger', '1501'),
  ('DB Cross Body Hammer Curls', 'DB Cross Body Hammer Curls', 'strength', 'Arme', 'Kurzhantel', 'wger', '1502'),
  ('Dumbbell Frog Press', 'Dumbbell Frog Press', 'strength', 'Beine', 'Kurzhantel', 'wger', '1503'),
  ('Bradford-Drücken mit Kurzhanteln', 'Dumbbell Bradford press', 'strength', 'Schultern', 'Kurzhantel', 'wger', '1504'),
  ('Kabelzug-Fly für die mittlere Brust', 'Cable Fly Middle Chest', 'strength', 'Brust', null, 'wger', '1689'),
  ('Kabelzug-Fly für die obere Brust', 'Cable Fly Upper Chest', 'strength', 'Brust', null, 'wger', '1690'),
  ('High-Incline Smith Machine Press', 'High-Incline Smith Machine Press', 'strength', 'Brust', null, 'wger', '1508'),
  ('Trizeps-Kickback am Kabelzug', 'Cable Tricep Kickback', 'strength', 'Arme', null, 'wger', '1509'),
  ('Neutral Grip Lat Pulldown', 'Neutral Grip Lat Pulldown', 'strength', 'Rücken', null, 'wger', '1510'),
  ('Kong Curl', 'Kong Curl', 'strength', 'Arme', 'Kurzhantel', 'wger', '1511'),
  ('Drop Curl', 'Drop Curl', 'strength', 'Arme', 'Kurzhantel', 'wger', '1512'),
  ('Trizepsdrücken über Kopf am Kabelzug', 'Overhead Cable Tricep Extension', 'strength', 'Arme', null, 'wger', '1513'),
  ('Seitwärtsgehen (Lateral Walk)', 'Lateral Walk', 'strength', 'Rücken', null, 'wger', '1514'),
  ('Leg Press Toe Press', 'Leg Press Toe Press', 'strength', 'Beine', null, 'wger', '1515'),
  ('Handstand', 'Handstand', 'strength', 'Schultern', null, 'wger', '1516'),
  ('Kabelzug-Fly für die untere Brust', 'Cable Fly Lower Chest', 'strength', 'Brust', null, 'wger', '1691'),
  ('Trizepsstrecken über Kopf', 'Overhead Triceps Extension', 'strength', 'Arme', 'SZ-Stange', 'wger', '1519'),
  ('Statisches Halten auf der Schrägbank', 'Incline Static Hold', 'strength', 'Brust', 'Kurzhantel', 'wger', '1693'),
  ('Pendular hack', 'Pendular hack', 'strength', 'Beine', null, 'wger', '1521'),
  ('Brustdrücken an der Maschine (flach)', 'Flat Machine Press', 'strength', 'Brust', 'Bank', 'wger', '1694'),
  ('Schlitten schieben', 'Sled Push', 'cardio', 'Cardio', null, 'wger', '1523'),
  ('Battle Ropes', 'Battle Ropes', 'cardio', 'Cardio', null, 'wger', '1524'),
  ('Ball Slams', 'Ball Slams', 'cardio', 'Cardio', null, 'wger', '1525'),
  ('Ski-Maschine', 'Ski Machine', 'cardio', 'Cardio', null, 'wger', '1526'),
  ('Pendelkniebeube', 'Pendulum Squat', 'strength', 'Beine', 'Körpergewicht', 'wger', '1527'),
  ('Glute Drive', 'Glute Drive', 'strength', 'Beine', null, 'wger', '1528'),
  ('Toes to bar', 'Toes to bar', 'strength', 'Bauch', 'Klimmzugstange', 'wger', '1529'),
  ('Liegende Kurzhantel-Curls', 'Lying Dumbbell Curls', 'strength', 'Arme', 'Bank, Kurzhantel', 'wger', '1530'),
  ('Cable Curls', 'Cable Curls', 'strength', 'Arme', 'Körpergewicht', 'wger', '1531'),
  ('Klimmzüge (weiter Griff)', 'Pull-Ups (Wide Grip)', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1695'),
  ('Langhantelrudern (Obergriff)', 'Barbell Row (Overhand)', 'strength', 'Rücken', 'Langhantel', 'wger', '1698'),
  ('Langhantelrudern (Untergriff)', 'Barbell Row (Underhand)', 'strength', 'Rücken', 'Langhantel', 'wger', '1699'),
  ('Delt Stretch', 'Delt Stretch', 'strength', 'Schultern', null, 'wger', '1536'),
  ('Pull-up Isometric Hold', 'Pull-up Isometric Hold', 'strength', 'Rücken', 'Klimmzugstange', 'wger', '1537'),
  ('Rumänisches Kreuzheben mit Langhantel (RDL)', 'Barbell Romanian Deadlift (RDL)', 'strength', 'Rücken', 'Langhantel', 'wger', '1700'),
  ('Schweres einarmiges Rudern', 'One-Arm Heavy Row', 'strength', 'Rücken', 'Kurzhantel', 'wger', '1701'),
  ('Latzug zur Brust mit weitem Griff', 'Jalón al pecho con agarre ancho', 'strength', 'Rücken', null, 'wger', '1702'),
  ('Kickbacks (Trizepsdrücken nach hinten)', 'Patadas traseras', 'strength', 'Arme', 'Bank, Kurzhantel', 'wger', '1703'),
  ('Tuck L-Sit', 'Tuck L-sit', 'strength', 'Bauch', 'Bank', 'wger', '1704'),
  ('Archer-Klimmzug', 'Archer Pull Up', 'strength', 'Rücken', null, 'wger', '1545'),
  ('Larsen Press', 'Larsen Press', 'strength', 'Brust', 'Langhantel', 'wger', '1546'),
  ('Bulgarische Kniebeuge mit Kurzhanteln', 'Bulgarian Squat with Dumbbells', 'strength', 'Beine', 'Kurzhantel', 'wger', '1706'),
  ('Stair Master', 'Stair Master', 'cardio', 'Cardio', 'Körpergewicht', 'wger', '1548'),
  ('Elevación lateral polea', 'Elevación lateral polea', 'strength', 'Rücken', 'Schrägbank', 'wger', '1707'),
  ('Butcher''s Block Dehnung', 'Butchers Block Stretch', 'strength', 'Schultern', 'Bank', 'wger', '1710'),
  ('Liegestütz mit Klatschen', 'Clap Push-UP', 'strength', 'Brust', 'Körpergewicht', 'wger', '1554'),
  ('Sleeper Stretch', 'Sleeper Stretch', 'strength', 'Schultern', 'Körpergewicht', 'wger', '1711'),
  ('Devil''s Press', 'Devil’s Press', 'strength', 'Schultern', 'Kurzhantel', 'wger', '1556'),
  ('Bird Dog', 'Bird Dog', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1572'),
  ('Bauchroller', 'Ab wheel', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1573'),
  ('Schwimmen', 'Schwimmen', 'cardio', 'Cardio', null, 'wger', '1574'),
  ('Standing Dowel Shoulder press', 'Standing Dowel Shoulder press', 'strength', 'Schultern', 'Langhantel', 'wger', '1575'),
  ('Snap Down', 'Snap Down', 'strength', 'Beine', null, 'wger', '1576'),
  ('Bretzel-Dehnung', 'Bretzel stretch', 'strength', 'Rücken', null, 'wger', '1577'),
  ('Hip Hinge', 'Hip hinge', 'strength', 'Beine', 'Langhantel', 'wger', '1578'),
  ('Bronco', 'Bronco', 'cardio', 'Cardio', 'Körpergewicht', 'wger', '1579'),
  ('Einarmiges Landmine-Rudern (senkrecht)', 'Perpendicular Unilateral Landmine Row', 'strength', 'Schultern', 'Langhantel', 'wger', '1580'),
  ('Trapez-Press', 'Trap press', 'strength', 'Schultern', 'Langhantel, Bank, Kurzhantel', 'wger', '1581'),
  ('Innenrotation in Seitenlage', 'Side-laying interior rotation', 'strength', 'Schultern', 'Langhantel, Bank, Kurzhantel', 'wger', '1582'),
  ('Supine press', 'Supine press', 'strength', 'Rücken', 'Langhantel, Bank', 'wger', '1583'),
  ('Auf der Stelle marschieren oder joggen', 'March or jog in place', 'cardio', 'Cardio', 'Körpergewicht', 'wger', '1584'),
  ('Leg and hip stretch', 'Leg and hip stretch', 'strength', 'Beine', 'Körpergewicht', 'wger', '1589'),
  ('Arm- und Nackendehnung', 'Arm and neck stretch', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1590'),
  ('Deep breathing (standing or seated)', 'Deep breathing (standing or seated)', 'strength', 'Brust', 'Körpergewicht', 'wger', '1591'),
  ('Geführte oder freie Meditation', 'Guided or free meditation', 'cardio', 'Cardio', 'Körpergewicht', 'wger', '1592'),
  ('Split-Kniebeuge an der Smith-Maschine', 'Smith Machine Split Squat', 'strength', 'Beine', 'Langhantel', 'wger', '1593'),
  ('Klimmzüge (neutraler Griff)', 'Pull-Ups (Neutral Grip)', 'strength', 'Rücken', null, 'wger', '1696'),
  ('Reverse Fly im Stehen', 'Reverse Fly Standing', 'strength', 'Schultern', 'Widerstandsband', 'wger', '1709'),
  ('Dehnung der horizontalen Schulterflexion', 'Horizontal Shoulder Flexion Stretch', 'strength', 'Schultern', 'Körpergewicht', 'wger', '1712'),
  ('Jalon caballero unialteral', 'Jalon caballero unialteral', 'strength', 'Rücken', 'Kurzhantel', 'wger', '1719'),
  ('Kurzhantel-Scaption', 'Dumbbell Scaption', 'strength', 'Schultern', 'Kurzhantel', 'wger', '1602'),
  ('Leg curl with elastic', 'Leg curl with elastic', 'strength', 'Waden', 'Widerstandsband', 'wger', '1603'),
  ('Seitlicher Ausfallschritt mit Slider', 'Sliding Lateral Lunge', 'strength', 'Beine', 'Langhantel', 'wger', '1604'),
  ('Copenhagen-Adduktion', 'Copenhagen Adduction Exercise', 'strength', 'Beine', 'Bank', 'wger', '1605'),
  ('Armheben (T/Y/I)', 'Arm Raises (T/Y/I)', 'strength', 'Arme', 'Körpergewicht', 'wger', '1606'),
  ('Typewriter-Klimmzüge', 'Typewriter Pull-ups', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1607'),
  ('Bizeps-Curl mit dem eigenen Körpergewicht', 'Bodyweight Biceps Curl', 'strength', 'Arme', 'Körpergewicht', 'wger', '1608'),
  ('Glute Kickback (Machine)', 'Glute Kickback (Machine)', 'strength', 'Beine', null, 'wger', '1723'),
  ('Adduktion im Stehen (Kabelzug)', 'Standing Adduction (Cable)', 'strength', 'Beine', null, 'wger', '1724'),
  ('Rudern im Sitzen (Maschine)', 'Seated Row (Machine)', 'strength', 'Rücken', null, 'wger', '1725'),
  ('Sumo-Kreuzheben mit Kettlebell', 'kettlebell sumo deadlift', 'strength', 'Beine', 'Kettlebell', 'wger', '1612'),
  ('Glute Kickback mit Widerstandsband', 'rubber band glute kickback', 'strength', 'Beine', 'Widerstandsband', 'wger', '1613'),
  ('Cat-Cow', 'Cat-Cow', 'strength', 'Rücken', null, 'wger', '1938'),
  ('Laufband-Cardio', 'Treadmill Cardio', 'cardio', 'Cardio', 'Körpergewicht', 'wger', '1615'),
  ('Eselstritt mit Kurzhantel', 'Dumbbell donkey kick', 'strength', 'Beine', 'Kurzhantel', 'wger', '1616'),
  ('SMR Glutes (lax ball)', 'SMR Glutes (lax ball)', 'strength', 'Beine', null, 'wger', '1952'),
  ('Cardio auf dem Heimtrainer', 'Stationary bike cardio', 'cardio', 'Cardio', 'Körpergewicht', 'wger', '1618'),
  ('Überzüge mit gestreckten Armen am Kabelzug', 'Straight-Arm Pulldown (Cable)', 'strength', 'Rücken', null, 'wger', '1726'),
  ('Sitzendes Wadenheben mit Kurzhantel', 'Seated Dumbbell Calf Raise', 'strength', 'Waden', 'Kurzhantel', 'wger', '1620'),
  ('Einarmiges Rudern am Kabelzug', 'Unilateral Cable row', 'strength', 'Rücken', 'Bank', 'wger', '1621'),
  ('Seitlicher Überzug mit gestrecktem Arm am Kabelzug', 'Side Straight-Arm Pulldown (Cable)', 'strength', 'Rücken', null, 'wger', '1727'),
  ('Innenrotation der Schulter am Kabelzug', 'Shoulder Internal Rotation (Cable)', 'strength', 'Schultern', null, 'wger', '1728'),
  ('Außenrotation der Schulter am Kabelzug', 'Shoulder External Rotation (Cable)', 'strength', 'Schultern', null, 'wger', '1729'),
  ('Side Lateral Raise (Cable)', 'Side Lateral Raise (Cable)', 'strength', 'Rücken', null, 'wger', '1730'),
  ('Front Raise (Cable)', 'Front Raise (Cable)', 'strength', 'Schultern', null, 'wger', '1731'),
  ('Face Pulls mit gelbem/grünem Band', 'Face pulls with yellow/green band', 'strength', 'Rücken', 'Widerstandsband', 'wger', '1732'),
  ('Isometrische Kniebeuge bis zum Muskelversagen', 'Isometric Squat to Failure', 'strength', 'Beine', 'Körpergewicht', 'wger', '1733'),
  ('Einbeiniger Ausfallschritt mit Kettlebell', 'Single-Leg Lunge with Kettlebell:', 'strength', 'Beine', 'Kettlebell', 'wger', '1734'),
  ('Einbeinige seitliche Gesäßpresse', 'Single-leg side glute press', 'strength', 'Beine', 'Schrägbank', 'wger', '1735'),
  ('Assisted chin-ups', 'Assisted chin-ups', 'strength', 'Rücken', null, 'wger', '1737'),
  ('Klimmzüge im neutralen Griff oder TRX-Rudern', 'Neutral-grip pull-ups or TRX rows', 'strength', 'Arme', 'Klimmzugstange', 'wger', '1738'),
  ('Shrimp Squad', 'Shrimp Squad', 'strength', 'Beine', 'Körpergewicht', 'wger', '1739'),
  ('L-Sit Pull-ups', 'L-Sit Pull-ups', 'strength', 'Arme', 'Körpergewicht', 'wger', '1741'),
  ('Back Lever', 'Back Lever', 'strength', 'Rücken', 'Klimmzugstange, Körpergewicht', 'wger', '1742'),
  ('Scheibenwischer', 'Windshield Wipers', 'strength', 'Bauch', 'Klimmzugstange, Körpergewicht', 'wger', '1743'),
  ('Seitheben an der Maschine', 'Machine Side Lateral Raises', 'strength', 'Schultern', null, 'wger', '1744'),
  ('Frontheben am Kabelzug mit kurzer Stange', 'Cable Front Raise with a small bar', 'strength', 'Schultern', null, 'wger', '1745'),
  ('Kniebeuge in der Multipresse', 'Smith machine squat', 'strength', 'Beine', null, 'wger', '1747'),
  ('Cable Pull Through', 'Cable pull through', 'strength', 'Beine', null, 'wger', '1751'),
  ('Side lateral raise - Front (Cable)', 'Side lateral raise - Front (Cable)', 'strength', 'Schultern', null, 'wger', '1752'),
  ('Side lateral raise - Back (Cable)', 'Side lateral raise - Back (Cable)', 'strength', 'Schultern', null, 'wger', '1753'),
  ('45° lateral raises', '45° lateral raises', 'strength', 'Schultern', 'Kurzhantel', 'wger', '1754'),
  ('Shoulder Y-pull cable', 'Shoulder Y-pull cable', 'strength', 'Schultern', null, 'wger', '1755'),
  ('Unterarmstütz mit Armheben', 'Plank Reach', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1766'),
  ('Reverse Crunch', 'Reverse crunch', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1772'),
  ('Legend Incline Bench Press', 'Legend Incline Bench Press', 'strength', 'Brust', null, 'wger', '1773'),
  ('Einbeiniges Kreuzheben mit Kurzhantel', 'Single-Leg Deadlift with Dumbbell', 'strength', 'Beine', 'Kurzhantel', 'wger', '1736'),
  ('Single Leg Glute Bridge', 'Single Leg Glute Bridge', 'strength', 'Beine', 'Körpergewicht', 'wger', '1740'),
  ('Hüftabduktion an der Maschine', 'Machine Hip Abduction', 'strength', 'Beine', null, 'wger', '1748'),
  ('Handgelenk-Curl am Kabelzug', 'Wrist curl, cable', 'strength', 'Arme', null, 'wger', '1771'),
  ('Dips am Stuhl', 'Chair dips', 'strength', 'Schultern', 'Körpergewicht', 'wger', '1774'),
  ('Reverse Butterfly für die hintere Schulter', 'Pec deck rear delt fly', 'strength', 'Schultern', null, 'wger', '1775'),
  ('Deficit Push ups', 'Deficit Push ups', 'strength', 'Brust', 'Körpergewicht', 'wger', '1777'),
  ('Schmetterlingsdehnung', 'Butterfly Stretch', 'strength', 'Beine', 'Körpergewicht', 'wger', '1843'),
  ('Froschdehnung', 'Frog Stretch', 'strength', 'Beine', 'Körpergewicht', 'wger', '1844'),
  ('Landmine-Rotation', 'Landmine Rotation', 'strength', 'Bauch', 'Langhantel', 'wger', '1779'),
  ('Supino inclinado', 'Supino inclinado', 'strength', 'Brust', null, 'wger', '1778'),
  ('Einarmiger Cable Pulldown über Kreuz', 'unilateral cross body cable pull down', 'strength', 'Schultern', null, 'wger', '1795'),
  ('Stützhalt an den Ringen', 'Ring Support Hold', 'strength', 'Brust', null, 'wger', '1832'),
  ('Beinbeuger am Boden mit Glidern', 'Floor Glider Hamstring Curls', 'strength', 'Schultern', null, 'wger', '1833'),
  ('Trap-Bar-Kniebeuge', 'Trap Bar Squat', 'strength', 'Beine', null, 'wger', '1803'),
  ('Wippen in die Sprunggelenk-Dorsalflexion', 'ankle dorsiflexion rocks', 'strength', 'Beine', 'Körpergewicht', 'wger', '1804'),
  ('Halten am Barren', 'Parallel Bar Hold', 'strength', 'Arme', null, 'wger', '1808'),
  ('Umgekehrte Hyperextension', 'Reverse Hyperextension', 'strength', 'Beine', 'Bank', 'wger', '1809'),
  ('Sphinx', 'Sphinx', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1810'),
  ('Buch aufschlagen (Open Book)', 'Open Book', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1822'),
  ('Tate Press mit Kurzhanteln', 'Dumbell Tate Press', 'strength', 'Arme', 'Bank, Kurzhantel', 'wger', '1824'),
  ('Reverse Flys für die hintere Schulter mit Brustauflage', 'Chest-Supported Rear Delt Raise', 'strength', 'Schultern', 'Bank, Kurzhantel', 'wger', '1825'),
  ('Band Pull-Apart mit Außenrotation', 'Band pull-apart with external rotation', 'strength', 'Schultern', 'Widerstandsband', 'wger', '1826'),
  ('Bauchpresse mit beiden Beinen', 'Double-Leg Abdominal Press', 'strength', 'Bauch', 'Matte, Körpergewicht', 'wger', '1827'),
  ('Bauchnabel einziehen', 'Abdominal Draw-In', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1828'),
  ('Landmine Kniebeuge mit Überkopfdrücken', 'Landmine Squat to Press', 'strength', 'Beine', 'Langhantel', 'wger', '1829'),
  ('Ausfallschritt nach hinten mit Langhantel', 'Barbell Step Back Lunge', 'strength', 'Beine', 'Langhantel', 'wger', '1830'),
  ('Hammer-Strength-Bankdrücken negativ (Decline)', 'Hammerstrength Decline Chest Press', 'strength', 'Brust', null, 'wger', '1831'),
  ('Trap-3-Raise', 'Trap-3 Raise', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1834'),
  ('Dehnung mit Außenrotation', 'External Rotation Stretch', 'strength', 'Schultern', 'Langhantel', 'wger', '1835'),
  ('Schulterübungen mit Band', 'Banded Shoulder Drills', 'strength', 'Schultern', 'Widerstandsband', 'wger', '1838'),
  ('Solo Hip Flexor Stretch', 'Solo Hip Flexor Stretch', 'strength', 'Beine', 'Körpergewicht', 'wger', '1839'),
  ('Bent-Leg Hamstring Stretch', 'Bent-Leg Hamstring Stretch', 'strength', 'Beine', 'Körpergewicht', 'wger', '1840'),
  ('Sitzende Schulterextensions-Dehnung', 'Seated Shoulder Extension Stretch', 'strength', 'Schultern', 'Körpergewicht', 'wger', '1841'),
  ('Reiterstellung (Seitspagat)', 'Horse Stance (Side Splits)', 'strength', 'Beine', 'Körpergewicht', 'wger', '1846'),
  ('Calves foam roller', 'Calves foam roller', 'strength', 'Beine', 'Körpergewicht', 'wger', '1854'),
  ('Hamstring Foam roller', 'Hamstring Foam roller', 'strength', 'Beine', 'Körpergewicht', 'wger', '1855'),
  ('Foam Roller Anterior tibialis', 'Foam Roller Anterior tibialis', 'strength', 'Beine', 'Körpergewicht', 'wger', '1856'),
  ('Foam Roller Iliotibial band', 'Foam Roller Iliotibial band', 'strength', 'Beine', 'Körpergewicht', 'wger', '1857'),
  ('Foam Roller quadriceps', 'Foam Roller quadriceps', 'strength', 'Beine', 'Körpergewicht', 'wger', '1858'),
  ('Foam Roller Gluteus', 'Foam Roller Gluteus', 'strength', 'Beine', 'Körpergewicht', 'wger', '1859'),
  ('Foam Roller Adductors', 'Foam Roller Adductors', 'strength', 'Beine', 'Körpergewicht', 'wger', '1860'),
  ('Side stretch', 'Side stretch', 'strength', 'Rücken', null, 'wger', '1861'),
  ('Hip Circles', 'Hip Circles', 'strength', 'Beine', null, 'wger', '1862'),
  ('Hip Crossover', 'Hip Crossover', 'strength', 'Beine', null, 'wger', '1863'),
  ('Ankle Roll', 'Ankle Roll', 'strength', 'Beine', null, 'wger', '1864'),
  ('Banded Ankle Mobility', 'Banded Ankle Mobility', 'strength', 'Beine', null, 'wger', '1865'),
  ('Hip Flexor Stretch', 'Hip Flexor Stretch', 'strength', 'Beine', null, 'wger', '1867'),
  ('Lunge with Twist Stretch', 'Lunge with Twist Stretch', 'strength', 'Beine', null, 'wger', '1868'),
  ('Lying Figure Four Stretch', 'Lying Figure Four Stretch', 'strength', 'Beine', null, 'wger', '1869'),
  ('Lying Hamstring Stretch with Band', 'Lying Hamstring Stretch with Band', 'strength', 'Beine', null, 'wger', '1870'),
  ('Pigeon Stretch', 'Pigeon Stretch', 'strength', 'Beine', null, 'wger', '1872'),
  ('Quad Stretch', 'Quad Stretch', 'strength', 'Beine', null, 'wger', '1873'),
  ('Runners Lunge Stretch', 'Runners Lunge Stretch', 'strength', 'Beine', null, 'wger', '1874'),
  ('Standing IT Band Stretch', 'Standing IT Band Stretch', 'strength', 'Beine', null, 'wger', '1875'),
  ('Supported Calf Stretch', 'Supported Calf Stretch', 'strength', 'Waden', null, 'wger', '1876'),
  ('Schulter-Rückzieher', 'Banded Scapular Retraction', 'strength', 'Rücken', 'Widerstandsband', 'wger', '1877'),
  ('Y-Raise mit Kurzhanteln auf der Schrägbank', 'Incline DB Y-Raise', 'strength', 'Schultern', 'Kurzhantel', 'wger', '1879')
on conflict (external_id) where external_id is not null do update set
  name_de = excluded.name_de,
  name_en = excluded.name_en,
  exercise_type = excluded.exercise_type,
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  updated_at = now();

insert into exercise_catalog (name_de, name_en, exercise_type, muscle_group, equipment, source, external_id)
values
  ('Handgelenkstreckung mit Kurzhanteln', 'DB Wrist Extension', 'strength', 'Arme', 'Kurzhantel', 'wger', '1881'),
  ('Seitheben am hohen Kabelzug', 'High-Cable Lateral Raise', 'strength', 'Schultern', null, 'wger', '1882'),
  ('Suitcase Carry', 'Suitcase Carry', 'strength', 'Bauch', 'Kurzhantel', 'wger', '1776'),
  ('Seitheben am Kabelzug hinter dem Rücken', 'Behind the Back Cable Lateral Raise', 'strength', 'Schultern', null, 'wger', '1807'),
  ('Clamshell (Muschel)', 'Clamshell', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1823'),
  ('Clamshell mit Band', 'Banded Clamshell', 'strength', 'Beine', 'Widerstandsband', 'wger', '1842'),
  ('Stehendes Good Morning mit weitem Stand (Pancake)', 'Standing Pancake Good Morning', 'strength', 'Beine', 'Körpergewicht', 'wger', '1397'),
  ('Sitzendes Good Morning mit weitem Stand (Pancake)', 'Seated Pancake Good Morning', 'strength', 'Beine', 'Körpergewicht', 'wger', '1845'),
  ('Shinbox-Innenrotations-Dehnung', 'Shinbox IR Stretch', 'strength', 'Beine', 'Körpergewicht', 'wger', '1884'),
  ('YTWL-Übung', 'YTWL Exercise', 'strength', 'Schultern', 'Kurzhantel, Schrägbank', 'wger', '1885'),
  ('Hüftabduktion in Rückenlage', 'Supine Hip Abduction', 'strength', 'Beine', 'Kurzhantel', 'wger', '1886'),
  ('Neck CARs', 'Neck CARs', 'strength', 'Schultern', null, 'wger', '1939'),
  ('Kurzhantel-Reißen (Dumbbell Snatch)', 'dumbbell snatch', 'strength', 'Beine', 'Kurzhantel', 'wger', '1947'),
  ('Einbeinige Box-Kniebeuge', '1 Leg Box Squat', 'strength', 'Beine', 'Körpergewicht', 'wger', '1948'),
  ('Langhantel-Überkopfdrücken', 'Overhead Barbell Press', 'strength', 'Schultern', 'Langhantel', 'wger', '1893'),
  ('Limber 11', 'Limber 11', 'strength', 'Beine', null, 'wger', '1949'),
  ('Foam Roll IT Band', 'Foam Roll IT Band', 'strength', 'Beine', null, 'wger', '1950'),
  ('Bent-knee Iron Cross', 'Bent-knee Iron Cross', 'strength', 'Beine', null, 'wger', '1953'),
  ('Fire Hydrant Circles', 'Fire Hydrant Circles', 'strength', 'Beine', null, 'wger', '1956'),
  ('Sitzende Piriformis-Dehnung', 'Seated Piriformis Stretch', 'strength', 'Beine', null, 'wger', '1959'),
  ('Trizepsdrücken am Seil', 'Tricep Rope Pushdowns', 'strength', 'Arme', null, 'wger', '1900'),
  ('Umsetzen und Stoßen', 'Clean and Press', 'strength', 'Schultern', 'Langhantel', 'wger', '1901'),
  ('Liegestütze mit Zusatzgewicht', 'Weighted push-ups', 'strength', 'Brust', 'Körpergewicht', 'wger', '1902'),
  ('Pec Deck', 'Pec Deck', 'strength', 'Brust', null, 'wger', '1904'),
  ('Pullback', 'Pullback', 'strength', 'Rücken', null, 'wger', '1905'),
  ('Hüftbrücke', 'Hip Bridge', 'strength', 'Beine', 'Körpergewicht', 'wger', '1906'),
  ('Unilateral Lunges', 'Unilateral Lunges', 'strength', 'Beine', 'Körpergewicht', 'wger', '1907'),
  ('Butterfly Superman', 'Butterfly Superman', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1908'),
  ('Beinkreisen', 'Leg Wheel', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1909'),
  ('Kniender Superman', 'Kneeling Superman', 'strength', 'Rücken', 'Körpergewicht', 'wger', '1910'),
  ('Katzen-Plank', 'Cat Plank', 'strength', 'Beine', 'Körpergewicht', 'wger', '1911'),
  ('Rumpfrotation', 'Core Rotation', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1912'),
  ('Unilateral Hip Thrust', 'Unilateral Hip Thrust', 'strength', 'Beine', 'Körpergewicht', 'wger', '1913'),
  ('Isometrisches Halten am Barren', 'Isometria alle parallele', 'strength', 'Schultern', null, 'wger', '1914'),
  ('Hüftabduktion im Vierfüßlerstand', 'Quadruped Hip Abduction', 'strength', 'Waden', 'Widerstandsband, Körpergewicht', 'wger', '1915'),
  ('Tuck planche', 'Tuck planche', 'strength', 'Schultern', 'Körpergewicht', 'wger', '1916'),
  ('Butterfly am Kabelzug', 'Seated Cable chest fly', 'strength', 'Brust', null, 'wger', '1922'),
  ('3008 Abdominal Crunch', '3008 Abdominal Crunch', 'strength', 'Bauch', null, 'wger', '1924'),
  ('Langhantel-Silverback-Shrug', 'Barbell Silverback Shrug', 'strength', 'Schultern', 'Langhantel', 'wger', '1925'),
  ('Latzug mit Untergriff', 'Inverted Lat Pull Down', 'strength', 'Rücken', 'Klimmzugstange', 'wger', '1927'),
  ('Sitzendes Rudern mit V-Griff', 'Seated V-Grip Row', 'strength', 'Rücken', 'Widerstandsband', 'wger', '1928'),
  ('Unterstützter Klimmzug', 'Assisted Pull-Up', 'strength', 'Rücken', 'Widerstandsband', 'wger', '1929'),
  ('Kurzhantel-Curl', 'Dumbbell Curl', 'strength', 'Arme', 'Kurzhantel', 'wger', '1931'),
  ('Legend Chest Press', 'Legend Chest Press', 'strength', 'Brust', null, 'wger', '1918'),
  ('Bauchcrunch', 'Abdominal Crunch', 'strength', 'Bauch', 'Matte', 'wger', '1933'),
  ('Belt Squat', 'Belt Squat', 'strength', 'Beine', null, 'wger', '1935'),
  ('Arnold Press', 'Arnold Shoulder Press', 'strength', 'Schultern', 'Kurzhantel', 'wger', '20'),
  ('Barbell Hack Squats', 'Barbell Hack Squats', 'strength', 'Beine', 'Langhantel', 'wger', '43'),
  ('Stehende Ausfallschritte mit Langhantel', 'Barbell Lunges Standing', 'strength', 'Beine', 'Langhantel', 'wger', '46'),
  ('Trizepsdrücken KH Über Kopf', 'Barbell Triceps Extension', 'strength', 'Arme', 'Langhantel', 'wger', '50'),
  ('Langhantel-Handgelenkcurl mit Untergriff', 'Barbell Reverse Wrist Curl', 'strength', 'Arme', 'Langhantel, Bank', 'wger', '48'),
  ('Bizeps KH-Curls', 'Biceps Curls With Dumbbell', 'strength', 'Arme', 'Kurzhantel', 'wger', '92'),
  ('Rudern Vorgebeugt LH', 'Bent Over Rowing', 'strength', 'Rücken', 'Langhantel', 'wger', '83'),
  ('Rudern Einarmig KH', 'Bent Over Dumbbell Rows', 'strength', 'Rücken', 'Bank, Kurzhantel', 'wger', '81'),
  ('Bizeps Curls Mit SZ-Stange', 'Biceps Curls With SZ-bar', 'strength', 'Arme', 'SZ-Stange', 'wger', '94'),
  ('Vorgebeugtes Seitheben', 'Bent-over Lateral Raises', 'strength', 'Schultern', 'Bank, Kurzhantel', 'wger', '82'),
  ('Bankdrücken KH', 'Benchpress Dumbbells', 'strength', 'Brust', 'Bank, Kurzhantel', 'wger', '75'),
  ('Bizeps LH-Curls', 'Biceps Curls With Barbell', 'strength', 'Arme', 'Langhantel', 'wger', '91'),
  ('Beinheben auf der Schrägbank', 'Decline Bench Leg Raise', 'strength', 'Bauch', 'Schrägbank', 'wger', '1889'),
  ('Reverse Butterfly am Kabel (einarmig)', 'Cable Rear-Delt Fly (single arm)', 'strength', 'Schultern', null, 'wger', '1936'),
  ('Latzug Breit', 'Wide-grip Pulldown', 'strength', 'Rücken', null, 'wger', '723'),
  ('Extreme Pec Stretch', 'Extreme Pec Stretch', 'strength', 'Brust', null, 'wger', '1919'),
  ('Extreme Shoulder Stretch', 'Extreme Shoulder Stretch', 'strength', 'Schultern', null, 'wger', '1920'),
  ('Extreme Lat Stretch', 'Extreme Lat Stretch', 'strength', 'Rücken', null, 'wger', '1921'),
  ('Dumbbell Push-Up', 'Dumbbell Push-Up', 'strength', 'Brust', 'Kurzhantel', 'wger', '801'),
  ('Bankdrücken LH', 'Bench Press', 'strength', 'Brust', 'Langhantel, Bank', 'wger', '73'),
  ('Bankdrücken Eng', 'Bench Press Narrow Grip', 'strength', 'Arme', 'Langhantel, Bank', 'wger', '76'),
  ('Bizeps am Kabel', 'Biceps Curl With Cable', 'strength', 'Arme', null, 'wger', '95'),
  ('Trizeps Seildrücken Einarmig', 'One Arm Triceps Extensions on Cable', 'strength', 'Arme', null, 'wger', '803'),
  ('Reverse Butterfly am Kabel', 'Cable Rear Delt Fly', 'strength', 'Schultern', null, 'wger', '822'),
  ('Adduktoren-Maschine', 'Seated Hip Adduction', 'strength', 'Beine', null, 'wger', '12'),
  ('Bauch Stabilisation', 'Abdominal Stabilization', 'strength', 'Bauch', 'Matte', 'wger', '56'),
  ('Brücke Auf Dem Ball', 'Glute Bridge', 'strength', 'Beine', null, 'wger', '265'),
  ('Latzug Eng', 'Close-grip Lat Pull Down', 'strength', 'Rücken', null, 'wger', '158'),
  ('Goblet-Kniebeuge mit Scheibe', 'Braced Squat', 'strength', 'Beine', null, 'wger', '124'),
  ('Handgelenkstreckung', 'Barbell Wrist Curl', 'strength', 'Arme', 'Langhantel, Bank', 'wger', '51'),
  ('Wadendrücken an Beinpresse', 'Calf Press Using Leg Press Machine', 'strength', 'Waden', null, 'wger', '146'),
  ('Wadenheben an Hackenschmidt', 'Calf Raises on Hackenschmitt Machine', 'strength', 'Waden', null, 'wger', '148'),
  ('Butterfly Eng', 'Butterfly Narrow Grip', 'strength', 'Brust', null, 'wger', '137'),
  ('Crunch am TRX Oder Auf Ball', 'Ball crunches', 'strength', 'Bauch', null, 'wger', '165'),
  ('Butterfly', 'Butterfly', 'strength', 'Brust', null, 'wger', '135'),
  ('Crunches an Maschine', 'Crunches on Machine', 'strength', 'Bauch', null, 'wger', '172'),
  ('Crunches an Schrägbank', 'Incline Crunches', 'strength', 'Bauch', 'Schrägbank', 'wger', '171'),
  ('Butterfly Reverse', 'Butterfly Reverse', 'strength', 'Schultern', null, 'wger', '139'),
  ('Crunches', 'Crunches', 'strength', 'Bauch', 'Matte', 'wger', '167'),
  ('Crunches mit gestreckten Beinen', 'Crunches With Legs Up', 'strength', 'Bauch', null, 'wger', '174'),
  ('Defizit Kreuzheben', 'Deficit Deadlift', 'strength', 'Rücken', 'Langhantel', 'wger', '189'),
  ('Flutter Kicks', 'Flutter Kicks', 'strength', 'Bauch', null, 'wger', '235'),
  ('Kreuzheben', 'Deadlifts', 'strength', 'Rücken', 'Langhantel', 'wger', '184'),
  ('Diagonales Schulterdrücken', 'Diagonal Shoulder Press', 'strength', 'Schultern', 'Bank', 'wger', '193'),
  ('Goblet Squat mit Kurzhantel', 'Dumbbell Goblet Squat', 'strength', 'Beine', 'Kurzhantel', 'wger', '203'),
  ('Negativ Bankdrücken', 'Decline Bench Press Barbell', 'strength', 'Brust', 'Langhantel', 'wger', '185'),
  ('Negativ Bankdrücken KH', 'Decline Bench Press Dumbbell', 'strength', 'Brust', 'Kurzhantel', 'wger', '186'),
  ('Ausfallschritte Stehend', 'Dumbbell Lunges Standing', 'strength', 'Beine', 'Kurzhantel', 'wger', '205'),
  ('Fly With Cable', 'Fly With Cable', 'strength', 'Brust', null, 'wger', '237'),
  ('Ausfallschritte im Gehen', 'Dumbbell Lunges Walking', 'strength', 'Beine', 'Kurzhantel', 'wger', '206'),
  ('Negativ Fliegende Mit KH', 'Fly With Dumbbells, Decline Bench', 'strength', 'Brust', 'Kurzhantel', 'wger', '239'),
  ('Fliegende KH Flachbank', 'Fly With Dumbbells', 'strength', 'Brust', 'Kurzhantel', 'wger', '238'),
  ('Bizeps KH-Curls Schrägbank', 'Dumbbell Incline Curl', 'strength', 'Arme', 'Kurzhantel', 'wger', '204'),
  ('Trizepsstrecken mit Kurzhantel', 'Dumbbell Triceps Extension', 'strength', 'Arme', 'Kurzhantel', 'wger', '211'),
  ('Dips', 'Dips', 'strength', 'Brust', 'Körpergewicht', 'wger', '194'),
  ('Dips Zwischen 2 Bänke', 'Dips Between Two Benches', 'strength', 'Arme', 'Bank', 'wger', '197'),
  ('Frontheben Mit Scheibe', 'Front Raises with Plates', 'strength', 'Schultern', null, 'wger', '254'),
  ('Beinheben im Hang', 'Hanging Leg Raises', 'strength', 'Bauch', 'Klimmzugstange', 'wger', '283'),
  ('Frontheben am Kabel', 'Front Raises', 'strength', 'Schultern', 'Langhantel, Kurzhantel', 'wger', '256'),
  ('Hindu-Kniebeugen', 'Hindu Squats', 'strength', 'Beine', null, 'wger', '291'),
  ('Front Kniebeuge', 'Front Squats', 'strength', 'Beine', 'Langhantel', 'wger', '257'),
  ('Hammercurls am Seil', 'Hammercurls on Cable', 'strength', 'Arme', null, 'wger', '275'),
  ('Hammercurls', 'Hammer Curls', 'strength', 'Arme', 'Kurzhantel', 'wger', '272'),
  ('Frenchpress KH', 'Skullcrusher Dumbbells', 'strength', 'Arme', 'Bank, Kurzhantel', 'wger', '245'),
  ('Frenchpress SZ-Stange', 'Skullcrusher SZ-bar', 'strength', 'Arme', 'Bank, SZ-Stange', 'wger', '246'),
  ('Frontziehen Eng', 'Front Pull narrow', 'strength', 'Rücken', 'Langhantel, SZ-Stange', 'wger', '259'),
  ('Frontziehen Breit', 'Front pull wide', 'strength', 'Rücken', 'Langhantel, SZ-Stange', 'wger', '258'),
  ('Handstand-Liegestütz', 'Handstand Pushup', 'strength', 'Schultern', 'Körpergewicht', 'wger', '282'),
  ('Beinbeuger Liegend', 'Leg Curls (laying)', 'strength', 'Beine', null, 'wger', '365'),
  ('Lat Pull Down (Leaning Back)', 'Lat Pull Down (Leaning Back)', 'strength', 'Rücken', null, 'wger', '354'),
  ('Latzug', 'Lat Pull Down (Straight Back)', 'strength', 'Rücken', null, 'wger', '355'),
  ('Leg Curls (sitting)', 'Leg Curls (sitting)', 'strength', 'Beine', null, 'wger', '366'),
  ('Seitheben am Kabel, Einarmig', 'Lateral Rows on Cable, One Armed', 'strength', 'Schultern', null, 'wger', '349'),
  ('Seitheben KH', 'Lateral Raises', 'strength', 'Schultern', 'Kurzhantel', 'wger', '348'),
  ('Beinbeuger', 'Leg Curl', 'strength', 'Beine', null, 'wger', '364'),
  ('Seitheben zum Frontheben', 'Lateral-to-Front Raises', 'strength', 'Schultern', 'Kurzhantel', 'wger', '351'),
  ('Kniebeuge an Multipresse - Eng', 'Squats on Multipress', 'strength', 'Beine', null, 'wger', '341'),
  ('Fliegende KH Schrägbank', 'Incline Dumbbell Fly', 'strength', 'Brust', 'Kurzhantel, Schrägbank', 'wger', '308'),
  ('Negativ Plank Mit Abwechselnden Fuß-Kontakt', 'Incline Plank With Alternate Floor Touch', 'strength', 'Bauch', null, 'wger', '312'),
  ('Kettlebell Swings', 'Kettlebell Swings', 'strength', 'Beine', 'Kettlebell', 'wger', '331'),
  ('Leverage Machine Iso Row', 'Leverage Machine Iso Row', 'strength', 'Rücken', null, 'wger', '380'),
  ('Crunches an Negativbank', 'Negative Crunches', 'strength', 'Bauch', null, 'wger', '427'),
  ('Military Press mit SZ-Stange', 'Military Press mit SZ-Bar', 'strength', 'Schultern', 'SZ-Stange', 'wger', '418'),
  ('Liegestüzten Diamond', 'Diamond push ups', 'strength', 'Brust', 'Körpergewicht', 'wger', '386'),
  ('Beinheben Aufrecht', 'Leg Raises, Standing', 'strength', 'Bauch', null, 'wger', '378'),
  ('Leverage Machine Chest Press', 'Leverage Machine Chest Press', 'strength', 'Brust', null, 'wger', '379'),
  ('Beinheben Liegend', 'Leg Raises, Lying', 'strength', 'Bauch', 'Matte', 'wger', '377'),
  ('Beine heben', 'Leg Raise', 'strength', 'Beine', null, 'wger', '376'),
  ('Box Squat mit weitem Stand', 'Low Box Squat - Wide Stance', 'strength', 'Beine', 'Langhantel', 'wger', '397'),
  ('Beinbeuger Stehend', 'Leg Curls (standing)', 'strength', 'Beine', null, 'wger', '367'),
  ('Kniebeuge an Hackenschmidtmaschine', 'Leg Press on Hackenschmidt Machine', 'strength', 'Beine', null, 'wger', '375'),
  ('Beinpresse Eng', 'Leg Presses (narrow)', 'strength', 'Beine', null, 'wger', '373'),
  ('Beinpresse (weit)', 'Leg Presses (wide)', 'strength', 'Beine', null, 'wger', '374'),
  ('Beinpresse', 'Leg Press', 'strength', 'Beine', null, 'wger', '371'),
  ('Pendelay Rows', 'Pendelay Rows', 'strength', 'Rücken', 'Langhantel', 'wger', '448'),
  ('Rack Deadlift', 'Rack Deadlift', 'strength', 'Rücken', null, 'wger', '484'),
  ('Push Press', 'Push Press', 'strength', 'Schultern', null, 'wger', '478'),
  ('Pause Bench', 'Pause Bench', 'strength', 'Brust', 'Langhantel, Bank', 'wger', '445'),
  ('KH an Scottmaschine', 'Preacher Curls', 'strength', 'Arme', 'SZ-Stange', 'wger', '465'),
  ('Reverse Flys (hintere Schulter)', 'Rear Delt Raises', 'strength', 'Schultern', 'Kurzhantel', 'wger', '487'),
  ('Einbeinige Kniebeuge', 'Pistol Squat', 'strength', 'Beine', null, 'wger', '456'),
  ('Klimmzüge an Maschine', 'Pull Ups on Machine', 'strength', 'Rücken', null, 'wger', '477'),
  ('Klimmzüge', 'Pull-ups', 'strength', 'Rücken', 'Klimmzugstange', 'wger', '475'),
  ('Plank', 'Plank', 'strength', 'Bauch', 'Körpergewicht', 'wger', '458'),
  ('Schere', 'Scissors', 'strength', 'Bauch', null, 'wger', '545'),
  ('Rudern Sitzend, Eng', 'Rowing seated, narrow grip', 'strength', 'Rücken', null, 'wger', '512'),
  ('Reverse Bar Curl', 'Reverse Bar Curl', 'strength', 'Arme', 'SZ-Stange', 'wger', '493'),
  ('Renegade Row', 'Renegade Row', 'strength', 'Rücken', 'Kurzhantel', 'wger', '490'),
  ('T-Bar Rudern (breit)', 'Rowing, T-bar', 'strength', 'Rücken', null, 'wger', '513'),
  ('Trizepsdrücken im Sitzen', 'Seated Triceps Press', 'strength', 'Arme', 'Bank, Kurzhantel', 'wger', '549'),
  ('Rudern', 'Row', 'strength', 'Rücken', 'Langhantel, Kurzhantel, Klimmzugstange', 'wger', '508'),
  ('Rowing, Lying on Bench', 'Rowing, Lying on Bench', 'strength', 'Rücken', null, 'wger', '510'),
  ('Ring Dips', 'Ring Dips', 'strength', 'Arme', null, 'wger', '501'),
  ('Rumänisches Kreuzheben', 'Romanian Deadlift', 'strength', 'Beine', 'Langhantel', 'wger', '507'),
  ('Schultermaschine', 'Shoulder Press, on Machine', 'strength', 'Schultern', null, 'wger', '543'),
  ('Reverse Grip Bench Press', 'Reverse Grip Bench Press', 'strength', 'Brust', 'Langhantel, Bank', 'wger', '498'),
  ('HIIT', 'Run - Interval Training', 'cardio', 'Cardio', null, 'wger', '529'),
  ('Schrägbankdrücken LH', 'Incline Bench Press - Barbell', 'strength', 'Brust', 'Langhantel, Schrägbank', 'wger', '538'),
  ('Shotgun Row', 'Shotgun Row', 'strength', 'Rücken', null, 'wger', '562'),
  ('Splinter Sit-ups', 'Splinter Sit-ups', 'strength', 'Bauch', null, 'wger', '607'),
  ('Speed Deadlift', 'Speed Deadlift', 'strength', 'Beine', null, 'wger', '604'),
  ('Frontdrücken MP', 'Shoulder Press, on Multi Press', 'strength', 'Schultern', null, 'wger', '569'),
  ('Sit Ups', 'Sit-ups', 'strength', 'Bauch', null, 'wger', '591'),
  ('Schulterdrücken KH', 'Shoulder Press, Dumbbells', 'strength', 'Schultern', 'Kurzhantel', 'wger', '567'),
  ('Schulterdrücken LH', 'Shoulder Press, Barbell', 'strength', 'Schultern', 'Langhantel', 'wger', '566'),
  ('Einarmiger Scott-Curl', 'Single-arm Preacher Curl', 'strength', 'Arme', 'Kurzhantel', 'wger', '584'),
  ('Wadenheben Sitzend', 'Sitting Calf Raises', 'strength', 'Waden', null, 'wger', '590'),
  ('Liegestütze seitlich', 'Side to Side Push Ups', 'strength', 'Brust', null, 'wger', '583'),
  ('Enges Bankdrücken an der Multipresse', 'Smith Machine Close-grip Bench Press', 'strength', 'Arme', null, 'wger', '598'),
  ('Side Crunch', 'Side Crunch', 'strength', 'Bauch', 'Matte', 'wger', '576'),
  ('Shrugs LH', 'Shrugs, Barbells', 'strength', 'Schultern', 'Langhantel', 'wger', '571'),
  ('Shrugs an der MP', 'Shrugs on Multipress', 'strength', 'Schultern', null, 'wger', '575'),
  ('Shrugs KH', 'Shrugs, Dumbbells', 'strength', 'Schultern', 'Kurzhantel', 'wger', '572'),
  ('Schulterzucken', 'Shoulder Shrug', 'strength', 'Schultern', 'Körpergewicht', 'wger', '570'),
  ('Side Plank', 'Side Plank', 'strength', 'Bauch', 'Körpergewicht', 'wger', '580'),
  ('Lat-Ziehen Mit Gesteckten Armen Mit (Stange)', 'Straight-arm Pull Down (bar Attachment)', 'strength', 'Rücken', null, 'wger', '628'),
  ('Sumo Kniebeuge', 'Sumo Squats', 'strength', 'Beine', 'Körpergewicht', 'wger', '632'),
  ('Lat-Zug am Seil', 'Straight-arm Pull Down (rope Attachment)', 'strength', 'Rücken', null, 'wger', '629'),
  ('Sumo Kreuzheben', 'Sumo Deadlift', 'strength', 'Beine', null, 'wger', '630'),
  ('Hocksprung', 'Squat Thrust', 'strength', 'Beine', 'Körpergewicht', 'wger', '616'),
  ('Stiff-legged Deadlifts', 'Stiff-legged Deadlifts', 'strength', 'Beine', 'Langhantel', 'wger', '627'),
  ('Wadenheben Stehend', 'Standing Calf Raises', 'strength', 'Waden', null, 'wger', '622'),
  ('Tiefe Hocksprünge', 'Squat Jumps', 'strength', 'Beine', null, 'wger', '614'),
  ('Kniebeuge', 'Squats', 'strength', 'Beine', 'Langhantel', 'wger', '615'),
  ('Bizeps-Curl im Stehen', 'Standing Bicep Curl', 'strength', 'Arme', 'Kurzhantel', 'wger', '621'),
  ('Trizeps Seildrücken Mit Stange', 'Triceps Extensions on Cable With Bar', 'strength', 'Arme', null, 'wger', '660'),
  ('Handstand Gegen Die Wand', 'Wall Handstand', 'strength', 'Schultern', 'Körpergewicht', 'wger', '711'),
  ('Latzug im Untergriff', 'Underhand Lat Pull Down', 'strength', 'Rücken', null, 'wger', '684'),
  ('Aufrechtes Rudern mit Kurzhanteln', 'Upright Row w/ Dumbbells', 'strength', 'Schultern', 'Kurzhantel', 'wger', '694'),
  ('V-Bar Pulldown', 'V-Bar Pulldown', 'strength', 'Rücken', null, 'wger', '695'),
  ('Wadenheben, Einbenig', 'Calf raises, one legged', 'strength', 'Waden', null, 'wger', '702'),
  ('Rudern Aufrecht ß-Stange', 'Upright Row, SZ-bar', 'strength', 'Schultern', 'SZ-Stange', 'wger', '693'),
  ('Wall Pushup', 'Wall Pushup', 'strength', 'Arme', 'Körpergewicht', 'wger', '713'),
  ('Rudern Aufrecht MP', 'Upright Row, on Multi Press', 'strength', 'Schultern', null, 'wger', '691')
on conflict (external_id) where external_id is not null do update set
  name_de = excluded.name_de,
  name_en = excluded.name_en,
  exercise_type = excluded.exercise_type,
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  updated_at = now();

insert into exercise_catalog (name_de, name_en, exercise_type, muscle_group, equipment, source, external_id)
values
  ('Diaphragmatic Breathing', 'Diaphragmatic Breathing', 'cardio', 'Cardio', null, 'wger', '1940'),
  ('Konzentrations-Curls', 'Dumbbell Concentration Curl', 'strength', 'Arme', 'Kurzhantel', 'wger', '202'),
  ('Überkopfkniebeuge', 'Overhead Squat', 'strength', 'Beine', null, 'wger', '441'),
  ('Laufen an Laufband', 'Run - Treadmill', 'cardio', 'Cardio', null, 'wger', '530'),
  ('Schrägbankdrücken KH', 'Incline Bench Press - Dumbbell', 'strength', 'Brust', 'Kurzhantel, Schrägbank', 'wger', '537'),
  ('Trizeps Seildrücken', 'Triceps Extensions on Cable', 'strength', 'Arme', null, 'wger', '659'),
  ('TRX Rudern', 'Rowing with TRX band', 'strength', 'Rücken', 'Körpergewicht', 'wger', '674'),
  ('Wall Squat', 'Wall Squat', 'strength', 'Beine', 'Körpergewicht', 'wger', '718'),
  ('Crunches am Seil', 'Crunches With Cable', 'strength', 'Bauch', null, 'wger', '173'),
  ('Hammercurl mit Kurzhanteln, abwechselnd', 'Alternating dumbbell hammer curl', 'strength', 'Arme', 'Kurzhantel', 'wger', '1567'),
  ('Straddle L-Sit', 'Straddle L-Sit', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1847'),
  ('L-Sit', 'L-sit', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1852'),
  ('L-Sit (Foot Supported)', 'L-Sit (Foot Supported)', 'strength', 'Bauch', 'Körpergewicht', 'wger', '1853'),
  ('Roll-overs into V-sits', 'Roll-overs into V-sits', 'strength', 'Beine', null, 'wger', '1954'),
  ('Hüftbeuger-Dehnung mit erhöhtem hinterem Fuß', 'Rear-foot-elevated Hip Flexor Stretch', 'strength', 'Beine', null, 'wger', '1960'),
  ('Kurzhantel-Bodendrücken', 'Dumbbell Floor Press', 'strength', 'Brust', 'Kurzhantel', 'wger', '1084'),
  ('Seitneigung', 'Side bend', 'strength', 'Bauch', 'Kurzhantel', 'wger', '1188'),
  ('Tiefe Kniebeuge mit Langhantel', 'Barbell Full Squat', 'strength', 'Beine', 'Langhantel', 'wger', '1801'),
  ('Liegestütz', 'Push-Up', 'strength', 'Brust', 'Körpergewicht', 'wger', '1551'),
  ('Kickstand RDL', 'Kickstand RDL', 'strength', 'Beine', 'Langhantel', 'wger', '1688'),
  ('Beinstrecker Einbeinig', 'Single Leg Extension', 'strength', 'Beine', null, 'wger', '71')
on conflict (external_id) where external_id is not null do update set
  name_de = excluded.name_de,
  name_en = excluded.name_en,
  exercise_type = excluded.exercise_type,
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  updated_at = now();
